(()=>{'use strict';
const KEY='sug_partner_master_v1',REWARD_KEY='sug_rewards_v1';
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function state(){const s=read(KEY,{partners:[]});s.partners=Array.isArray(s.partners)?s.partners:[];return s}
function list({kind,activeOnly=false}={}){return state().partners.filter(p=>(!kind||p.kind===kind)&&(!activeOnly||p.active!==false)).sort((a,b)=>String(a.name).localeCompare(String(b.name),'ja'))}
function upsert(input){const s=state(),id=String(input.id||('p_'+Date.now().toString(36))).trim(),name=String(input.name||'').trim();if(!name)return{ok:false,reason:'NAME_REQUIRED'};const p={id,name,kind:['FOOD','BATH','CAFE','OTHER'].includes(input.kind)?input.kind:'FOOD',discountYen:Math.max(0,Math.round(Number(input.discountYen)||0)),points:Math.max(0,Math.round(Number(input.points)||0)),costYen:Math.max(0,Math.round(Number(input.costYen)||0)),monthlyLimit:Math.max(0,Math.round(Number(input.monthlyLimit)||0)),targetMenu:String(input.targetMenu||'').trim(),address:String(input.address||'').trim(),note:String(input.note||'').trim(),active:input.active!==false,updatedAt:new Date().toISOString()};const i=s.partners.findIndex(x=>x.id===id);if(i>=0)s.partners[i]={...s.partners[i],...p};else s.partners.push(p);write(KEY,s);window.dispatchEvent(new CustomEvent('sug:partners-change',{detail:p}));return{ok:true,partner:p}}
function remove(id){const s=state(),n=s.partners.length;s.partners=s.partners.filter(p=>p.id!==id);write(KEY,s);if(s.partners.length!==n)window.dispatchEvent(new CustomEvent('sug:partners-change'));return s.partners.length!==n}
function usageCount(partnerId,month){const r=read(REWARD_KEY,{redemptions:[]});return(r.redemptions||[]).filter(x=>x.partnerId===partnerId&&(!month||x.month===month)).length}
function monthKey(){return window.SuGPointsV2716?.monthKey?.()||new Date().toISOString().slice(0,7)}
function eligible(kind){const m=monthKey();return list({kind,activeOnly:true}).filter(p=>!p.monthlyLimit||usageCount(p.id,m)<p.monthlyLimit)}
function redeemPartner(partnerId){const p=state().partners.find(x=>x.id===partnerId);if(!p||p.active===false)return{ok:false,reason:'PARTNER_NOT_AVAILABLE'};const api=window.SuGPointsV2716;if(!api)return{ok:false,reason:'POINTS_NOT_READY'};const m=monthKey();if(p.monthlyLimit&&usageCount(p.id,m)>=p.monthlyLimit)return{ok:false,reason:'PARTNER_MONTHLY_LIMIT'};const w=api.wallet(),b=api.budget();if(Number(w.balance||0)<Number(p.points||0))return{ok:false,reason:'POINTS_LOW'};if(Number(b.usedCostYen||0)+Number(p.costYen||0)>Number(b.maxCostYen||20000))return{ok:false,reason:'MONTHLY_BUDGET'};const code=`SUGP-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;w.balance-=Number(p.points||0);w.events.unshift({id:`redeem:${code}`,points:-Number(p.points||0),category:'REDEEM',label:`${p.name} ${p.discountYen?`${p.discountYen}円OFF`:''}`.trim(),meta:{partnerId:p.id,costYen:p.costYen,code},at:new Date().toISOString(),day:api.dayKey(),month:m});write('sug_points_v1',w);b.usedCostYen=Number(b.usedCostYen||0)+Number(p.costYen||0);write('sug_points_budget_v1',b);const s=read(REWARD_KEY,{redemptions:[]}),r={code,partnerId:p.id,name:p.name,points:p.points,discountYen:p.discountYen,costYen:p.costYen,targetMenu:p.targetMenu,status:'ISSUED',at:new Date().toISOString(),month:m};s.redemptions=Array.isArray(s.redemptions)?s.redemptions:[];s.redemptions.unshift(r);s.redemptions=s.redemptions.slice(0,100);write(REWARD_KEY,s);window.dispatchEvent(new CustomEvent('sug:points-change',{detail:{wallet:w,redemption:r}}));return{ok:true,redemption:r,wallet:w,budget:b,partner:p}}
window.SuGPartnersV2722={state,list,upsert,remove,eligible,usageCount,redeemPartner,key:KEY};
})();