(()=>{'use strict';
const KEY='sug_rewards_v1',COST_KEY='sug_reward_costs_v1',LIMIT_KEY='sug_reward_limits_v1',VALIDITY_KEY='sug_reward_validity_v1';
const BASE=[
{id:'protein',name:'プロテイン',points:5000,costYen:null,defaultLimit:1,validityDays:30,kind:'BODY',delivery:'PICKUP',note:'継続記録の交換特典。実費設定後に交換可能。'},
{id:'meal1000',name:'提携飲食店 1,000円OFF',points:7000,costYen:1000,defaultLimit:2,validityDays:30,kind:'FOOD',delivery:'COUPON',note:'提携店・対象メニュー・利用条件を確認して発行。'},
{id:'powergrip',name:'パワーグリップ',points:15000,costYen:null,defaultLimit:1,validityDays:60,kind:'BODY',delivery:'PICKUP',note:'中長期継続向け。商品原価設定後に交換可能。'},
{id:'bracebelt',name:'腹圧ベルト',points:25000,costYen:null,defaultLimit:1,validityDays:60,kind:'BODY',delivery:'PICKUP',note:'長期継続向け。商品原価設定後に交換可能。'}
];
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function state(){const s=read(KEY,{redemptions:[]});s.redemptions=Array.isArray(s.redemptions)?s.redemptions:[];return s}
function obj(k){const v=read(k,{});return v&&typeof v==='object'&&!Array.isArray(v)?v:{}}
const costs=()=>obj(COST_KEY),limits=()=>obj(LIMIT_KEY),validities=()=>obj(VALIDITY_KEY);
function monthKey(){const api=window.SuGPointsV2716;return api?.monthKey?api.monthKey():new Date().toISOString().slice(0,7)}
function redeemedCount(id,month=monthKey()){return state().redemptions.filter(r=>r.rewardId===id&&r.month===month&&r.status!=='CANCELLED').length}
function validityDays(id){const d=BASE.find(x=>x.id===id);if(!d)return 30;const n=Number(validities()[id]);return Number.isFinite(n)&&n>=1&&n<=365?Math.round(n):d.validityDays}
function catalog(){const c=costs(),l=limits();return BASE.map(x=>{const override=Number(c[x.id]),cost=Number.isFinite(override)&&override>0?Math.round(override):x.costYen,lim=Number(l[x.id]),monthlyLimit=Number.isFinite(lim)&&lim>=0?Math.round(lim):x.defaultLimit,redeemedThisMonth=redeemedCount(x.id);return{...x,costYen:cost,costReady:Number.isFinite(Number(cost))&&Number(cost)>0,monthlyLimit,redeemedThisMonth,remainingExchanges:Math.max(0,monthlyLimit-redeemedThisMonth),validityDays:validityDays(x.id),requiresPartner:x.id==='meal1000'}})}
function setCost(id,yen){if(!BASE.some(x=>x.id===id))return{ok:false,reason:'NOT_FOUND'};const n=Math.round(Number(yen)||0);if(n<=0)return{ok:false,reason:'INVALID_COST'};const c=costs();c[id]=n;write(COST_KEY,c);window.dispatchEvent(new CustomEvent('sug:rewards-change'));return{ok:true,costYen:n}}
function setLimit(id,count){if(!BASE.some(x=>x.id===id))return{ok:false,reason:'NOT_FOUND'};const n=Math.round(Number(count));if(!Number.isFinite(n)||n<0||n>99)return{ok:false,reason:'INVALID_LIMIT'};const l=limits();l[id]=n;write(LIMIT_KEY,l);window.dispatchEvent(new CustomEvent('sug:rewards-change'));return{ok:true,monthlyLimit:n}}
function setValidity(id,days){if(!BASE.some(x=>x.id===id))return{ok:false,reason:'NOT_FOUND'};const n=Math.round(Number(days));if(!Number.isFinite(n)||n<1||n>365)return{ok:false,reason:'INVALID_VALIDITY'};const v=validities();v[id]=n;write(VALIDITY_KEY,v);window.dispatchEvent(new CustomEvent('sug:rewards-change'));return{ok:true,validityDays:n}}
function foodPartners(){const api=window.SuGPartnersV2722;return api?api.list({kind:'FOOD',activeOnly:true}):[]}
function normalize(r){if(!r)return null;const delivery=r.delivery||(r.partnerId?'COUPON':(r.kind==='FOOD'?'COUPON':'PICKUP'));return{...r,delivery}}
function redemption(code){const clean=String(code||'').trim().toUpperCase();return normalize(state().redemptions.find(r=>String(r.code||'').toUpperCase()===clean)||null)}
function isExpired(r){return !!r?.expiresAt&&new Date(r.expiresAt).getTime()<Date.now()}
function setFulfillment(code,status){if(!['USED','RECEIVED'].includes(status))return{ok:false,reason:'INVALID_STATUS'};const s=state(),r=s.redemptions.find(x=>String(x.code||'').toUpperCase()===String(code||'').trim().toUpperCase());if(!r)return{ok:false,reason:'NOT_FOUND'};const nr=normalize(r);if(nr.status==='USED'||nr.status==='RECEIVED')return{ok:false,reason:'ALREADY_FULFILLED',redemption:nr};if(isExpired(nr))return{ok:false,reason:'EXPIRED',redemption:nr};if(status==='USED'&&nr.delivery!=='COUPON')return{ok:false,reason:'WRONG_FULFILLMENT'};if(status==='RECEIVED'&&nr.delivery!=='PICKUP')return{ok:false,reason:'WRONG_FULFILLMENT'};r.status=status;r.updatedAt=new Date().toISOString();if(status==='USED')r.usedAt=r.updatedAt;else r.receivedAt=r.updatedAt;write(KEY,s);window.dispatchEvent(new CustomEvent('sug:rewards-change',{detail:{redemption:normalize(r)}}));return{ok:true,redemption:normalize(r)}}
function verifyCode(code,{partnerId=''}={}){const r=redemption(code);if(!r)return{ok:false,reason:String(code||'').trim()?'NOT_FOUND':'CODE_REQUIRED'};if(r.status==='USED'||r.status==='RECEIVED')return{ok:false,reason:'ALREADY_FULFILLED',redemption:r};if(isExpired(r))return{ok:false,reason:'EXPIRED',redemption:r};if(r.delivery==='COUPON'){if(!r.partnerId)return{ok:false,reason:'PARTNER_MISSING',redemption:r};if(partnerId&&String(r.partnerId)!==String(partnerId))return{ok:false,reason:'WRONG_PARTNER',redemption:r}}return{ok:true,redemption:r}}
function consumeCode(code,{partnerId=''}={}){const v=verifyCode(code,{partnerId});if(!v.ok)return v;return setFulfillment(v.redemption.code,v.redemption.delivery==='COUPON'?'USED':'RECEIVED')}
function redeem(id,options={}){const api=window.SuGPointsV2716;if(!api)return{ok:false,reason:'POINTS_NOT_READY'};const item=catalog().find(x=>x.id===id);if(!item)return{ok:false,reason:'NOT_FOUND'};let partner=null;if(item.requiresPartner){partner=foodPartners().find(p=>p.id===String(options.partnerId||''));if(!partner)return{ok:false,reason:'PARTNER_REQUIRED'}}if(!item.costReady)return{ok:false,reason:'COST_NOT_SET'};if(item.monthlyLimit<=0||item.redeemedThisMonth>=item.monthlyLimit)return{ok:false,reason:'MONTHLY_ITEM_LIMIT'};const w=api.wallet(),b=api.budget();if(Number(w.balance||0)<item.points)return{ok:false,reason:'POINTS_LOW'};if(Number(b.usedCostYen||0)+Number(item.costYen||0)>Number(b.maxCostYen||20000))return{ok:false,reason:'MONTHLY_BUDGET'};const s=state(),code=`SUG-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`,at=new Date();w.balance-=item.points;w.events.unshift({id:`redeem:${code}`,points:-item.points,category:'REDEEM',label:item.name,meta:{rewardId:item.id,costYen:item.costYen,code},at:at.toISOString(),day:api.dayKey(),month:api.monthKey()});write('sug_points_v1',w);b.usedCostYen=Number(b.usedCostYen||0)+Number(item.costYen||0);write('sug_points_budget_v1',b);const days=item.validityDays,r={code,rewardId:item.id,name:item.name,points:item.points,costYen:item.costYen,kind:item.kind,delivery:item.delivery,status:'ISSUED',at:at.toISOString(),month:api.monthKey(),validityDays:days,expiresAt:new Date(at.getTime()+days*86400000).toISOString()};if(partner){r.partnerId=partner.id;r.partnerName=partner.name;r.partnerAddress=partner.address||'';r.targetMenu=partner.targetMenu||''}s.redemptions.unshift(r);s.redemptions=s.redemptions.slice(0,100);write(KEY,s);window.dispatchEvent(new CustomEvent('sug:points-change',{detail:{wallet:w,redemption:r}}));window.dispatchEvent(new CustomEvent('sug:rewards-change',{detail:{redemption:r}}));return{ok:true,redemption:r,wallet:w,budget:b}}
window.SuGRewardsV2742={catalog,state,costs,limits,validities,setCost,setLimit,setValidity,validityDays,redeemedCount,foodPartners,redemption,isExpired,setFulfillment,verifyCode,consumeCode,redeem};
})();