name: SuGMember
options:
  bundleIdPrefix: jp.sugosaka
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: '17.0'
    SWIFT_VERSION: '5.0'
targets:
  SuGMember:
    type: application
    platform: iOS
    sources:
      - SuGMember
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: jp.sugosaka.member
        MARKETING_VERSION: '1.0.0'
        CURRENT_PROJECT_VERSION: '1'
        CODE_SIGN_ENTITLEMENTS: SuGMember/SuGMember.entitlements
        INFOPLIST_FILE: SuGMember/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        TARGETED_DEVICE_FAMILY: '1'
        SUPPORTS_MACCATALYST: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: SuGMember/SuGMember.entitlements
