(()=>{'use strict';
const DAILY='sug_body_daily_v1',NUT='sug_body_nutrition_weight_v1',WALLET='sug_points_v1';
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const day=()=>window.SuGPointsV2716?.dayKey?.()||new Date().toISOString().slice(0,10);
const in15=v=>Number.isFinite(+v)&&+v>=1&&+v<=5;
function flowComplete(s,d){return !!(s?.date===d&&in15(s.appetite)&&in15(s.precheck)&&[30,45,60,75].includes(+s.available)&&[1,2,3].includes(+s.level)&&['auto','push','pull','legs','shoulder','care'].includes(String(s.area||'')))}
function repairFalseFlowAward(s,d){if(flowComplete(s,d))return false;const w=read(WALLET,null);if(!w||!Array.isArray(w.events))return false;const bad=w.events.filter(e=>e.day===d&&e.meta?.source==='dailyCheck');if(!bad.length)return false;const pts=bad.reduce((a,e)=>a+Math.max(0,+e.points||0),0);w.events=w.events.filter(e=>!(e.day===d&&e.meta?.source==='dailyCheck'));w.balance=Math.max(0,(+w.balance||0)-pts);w.lifetime=Math.max(0,(+w.lifetime||0)-pts);write(WALLET,w);window.dispatchEvent(new CustomEvent('sug:points-change',{detail:{wallet:w,repair:'invalidDailyCheck',removedPoints:pts}}));return true}
function sync(){const P=window.SuGPointsV2716;if(!P)return null;const d=day(),s=read(DAILY,null),n=read(NUT,[]).find(x=>x.date===d);repairFalseFlowAward(s,d);if(s?.date===d){const recovery=[s.sleep,s.fatigue,s.stress,s.pain];if(recovery.every(in15))P.addAction(`daily:recovery:${d}`,'睡眠・疲労・ストレス・痛みを記録',100,{source:'dailyRecovery'});if(flowComplete(s,d))P.addAction(`daily:check:${d}`,'TODAY FLOW入力完了',100,{source:'dailyCheck'})}if(n){if(+n.weight>0)P.addAction(`daily:weight:${d}`,'体重記録',50,{source:'weightLog'});if(+n.kcal>0&&+n.p>0&&+n.f>0&&+n.c>0)P.addAction(`daily:nutrition:${d}`,'kcal・PFC記録',100,{source:'nutritionLog'})}return P.wallet()}
function render(){let c=document.getElementById('dailyActionPointCard');if(!c){const p=document.getElementById('weightGoalCard')||document.getElementById('nutritionWeightCard');if(!p)return;c=document.createElement('section');c.id='dailyActionPointCard';c.className='card';p.after(c)}sync();const P=window.SuGPointsV2716,w=P?.wallet?.(),d=day(),events=(w?.events||[]).filter(e=>e.day===d&&['dailyRecovery','dailyCheck','weightLog','nutritionLog','micronutrition'].includes(e.meta?.source));const labels={dailyRecovery:'回復評価',dailyCheck:'TODAY FLOW',weightLog:'体重',nutritionLog:'kcal・PFC',micronutrition:'微量栄養'};const got=events.reduce((a,e)=>a+(+e.points||0),0);c.innerHTML=`<div class="ey">DAILY ACTION · V27.47</div><h2>今日やること｜POINT</h2><div class="metric"><span>TODAY ACTION POINT</span><b>+${got}pt</b></div><div style="margin-top:12px">${Object.entries(labels).map(([k,v])=>{const e=events.find(x=>x.meta?.source===k);return `<div class="historyrow"><b>${v}</b><span>${e?`DONE +${e.points}pt`:'未完了'}</span></div>`}).join('')}</div><div class="sub" style="margin-top:10px">TODAY FLOWは食欲・時間・体感・操作レベル・鍛える場所がすべて有効入力のときだけ付与。</div>`}
let timer;const schedule=()=>{clearTimeout(timer);timer=setTimeout(render,120)};['sug:nutrition-weight','sug:points-change','sug:micronutrition'].forEach(x=>window.addEventListener(x,schedule));window.addEventListener('storage',e=>{if(!e.key||[DAILY,NUT].includes(e.key))schedule()});document.addEventListener('click',e=>{if(e.target?.closest?.('#appetite,#precheck,#sleep,#fatigue,#stress,#pain')||['nwSave','mnSave'].includes(e.target?.id)||['available','level','area'].includes(e.target?.id))setTimeout(schedule,160)});setTimeout(render,520);window.SuGDailyActionPointsV2747={sync,render,flowComplete,repairFalseFlowAward};
})();