(()=>{
'use strict';
const VERSION='27.79';
const ENDPOINT='https://sug-body-management-system.vercel.app/api/food-analyze';
const MEALS_KEY='sug_food_ai_meals_v2779';
const CFG='sug_body_food_ai_config_v1';
const n=(v,min=0,max=1e9)=>{v=Number(v);return Number.isFinite(v)?Math.max(min,Math.min(max,v)):null};
const day=()=>{const d=new Date(),p=x=>String(x).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(_){}};
function endpoint(){const c=read(CFG,{});return String(window.SUG_FOOD_AI_ENDPOINT||c.endpoint||ENDPOINT).trim()}
function meals(){return read(MEALS_KEY,[]).filter(x=>x?.date===day())}
function allMeals(){return read(MEALS_KEY,[])}
function saveMeal(m){const all=allMeals().filter(x=>x?.date&&x.id!==m.id);all.push(m);write(MEALS_KEY,all.slice(-120));return m}
function normalize(x){const m=x?.micronutrients||{};return{id:`${Date.now()}_${Math.random().toString(36).slice(2,7)}`,date:day(),dish:String(x?.dish||'食事').slice(0,120),portionNote:String(x?.portionNote||'').slice(0,240),confidence:n(x?.confidence,0,1),kcal:n(x?.kcal,0,5000),proteinG:n(x?.p??x?.proteinG,0,500),fatG:n(x?.f??x?.fatG,0,500),carbsG:n(x?.c??x?.carbsG,0,1000),fiberG:n(m.fiber??x?.fiberG,0,200),ironMg:n(m.iron??x?.ironMg,0,100),magnesiumMg:n(m.magnesium??x?.magnesiumMg,0,2000),zincMg:n(m.zinc??x?.zincMg,0,100),calciumMg:n(m.calcium??x?.calciumMg,0,3000),potassiumMg:n(m.potassium??x?.potassiumMg,0,10000),omega3G:n(m.omega3??x?.omega3G,0,20),foods:Array.isArray(x?.foods)?x.foods.slice(0,12):[],warnings:Array.isArray(x?.warnings)?x.warnings.slice(0,8):[],analyzedAt:new Date().toISOString(),estimated:true}}
function sum(key){return meals().reduce((s,x)=>s+(n(x?.[key])||0),0)}
function aggregate(){const list=meals();if(!list.length)return null;return{date:day(),kcal:sum('kcal'),proteinG:sum('proteinG'),fatG:sum('fatG'),carbsG:sum('carbsG'),fiberG:sum('fiberG'),ironMg:sum('ironMg'),magnesiumMg:sum('magnesiumMg'),zincMg:sum('zincMg'),calciumMg:sum('calciumMg'),potassiumMg:sum('potassiumMg'),omega3G:sum('omega3G'),mealCount:list.length,estimated:true,source:'food_photo_ai'}}
function syncNutrition(){const a=aggregate();if(!a)return null;try{window.SuGNutrition?.setDaily?.(a)}catch(_){}window.dispatchEvent(new CustomEvent('sug:nutrition',{detail:a}));return a}
function resize(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(new Error('READ_FAILED'));r.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error('IMAGE_FAILED'));img.onload=()=>{const max=1280,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale)),c=document.createElement('canvas');c.width=w;c.height=h;const g=c.getContext('2d');g.drawImage(img,0,0,w,h);resolve(c.toDataURL('image/jpeg',.78))};img.src=r.result};r.readAsDataURL(file)})}
async function analyzeDataUrl(imageDataUrl){const ep=endpoint();const res=await fetch(ep,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:VERSION,date:day(),imageDataUrl,request:{instruction:'Estimate this visible meal for nutrition logging. Return approximate kcal/P/F/C and available micronutrients. Do not claim laboratory precision.'}})});let body={};try{body=await res.json()}catch(_){}if(!res.ok){const e=new Error(body?.error||`HTTP_${res.status}`);e.status=res.status;throw e}const meal=saveMeal(normalize(body));syncNutrition();render();window.dispatchEvent(new CustomEvent('sug:food-photo-result',{detail:meal}));return meal}
function style(){if(document.getElementById('sugFoodPhotoStyle2779'))return;const s=document.createElement('style');s.id='sugFoodPhotoStyle2779';s.textContent=`.sugFoodBox{margin-top:11px;border-top:1px solid #24292d;padding-top:11px}.sugFoodBtn{appearance:none;width:100%;border:1px solid #6a5227;border-radius:12px;padding:11px;background:linear-gradient(135deg,#e7c36b,#9e7a31);color:#0d0d0e;font-size:10px;font-weight:1000}.sugFoodStatus{margin-top:8px;color:#858a91;font-size:8px;line-height:1.5}.sugFoodMeal{display:flex;justify-content:space-between;gap:10px;padding:8px 0;border-top:1px solid #24292d;font-size:9px}.sugFoodMeal b{color:#eee}.sugFoodMeal span{color:#b9d8e8;white-space:nowrap}.sugFoodTotals{display:flex;gap:6px;overflow:auto;margin-top:8px}.sugFoodChip{flex:0 0 auto;border:1px solid #2e4b5e;border-radius:999px;padding:6px 8px;background:#0b151c;color:#c9e2ef;font-size:8px}`;document.head.appendChild(s)}
function host(){return document.querySelector('#sugNutrition2778 .sugNutIn')||document.getElementById('sugNutrition2778')}
function mount(){style();const h=host();if(!h||document.getElementById('sugFoodPhoto2779'))return;const box=document.createElement('div');box.id='sugFoodPhoto2779';box.className='sugFoodBox';box.innerHTML=`<input id="sugFoodFile2779" type="file" accept="image/*" capture="environment" hidden><button id="sugFoodTake2779" class="sugFoodBtn">食事写真を撮る / 選ぶ</button><div id="sugFoodStatus2779" class="sugFoodStatus">写真は解析時だけ送信し、端末には栄養推定結果のみ保存します。</div><div id="sugFoodTotals2779" class="sugFoodTotals"></div><div id="sugFoodList2779"></div>`;h.insertBefore(box,h.firstChild);const input=box.querySelector('#sugFoodFile2779'),btn=box.querySelector('#sugFoodTake2779'),st=box.querySelector('#sugFoodStatus2779');btn.onclick=()=>input.click();input.onchange=async()=>{const f=input.files?.[0];if(!f)return;btn.disabled=true;st.textContent='写真を軽量化しています…';try{const data=await resize(f);st.textContent='AI解析中…';const m=await analyzeDataUrl(data);st.textContent=`追加しました：${m.dish} ${m.kcal==null?'':Math.round(m.kcal)+' kcal'}`}catch(e){const map={AI_NOT_CONFIGURED:'AIサーバー設定が未完了です',IMAGE_REQUIRED:'画像を読み取れませんでした',IMAGE_TOO_LARGE:'画像が大きすぎます',AI_UPSTREAM:'AI解析サーバーでエラーが発生しました',AI_FAILED:'AI解析に失敗しました'};st.textContent=map[e.message]||`解析できませんでした（${e.message}）`}finally{btn.disabled=false;input.value=''}};render()}
function render(){mount();const list=meals(),a=aggregate(),tot=document.getElementById('sugFoodTotals2779'),el=document.getElementById('sugFoodList2779');if(tot)tot.innerHTML=a?[['KCAL',Math.round(a.kcal)],['P',Math.round(a.proteinG)+'g'],['F',Math.round(a.fatG)+'g'],['C',Math.round(a.carbsG)+'g']].map(x=>`<span class="sugFoodChip">${x[0]} ${x[1]}</span>`).join(''):'';if(el)el.innerHTML=list.slice().reverse().map(x=>`<div class="sugFoodMeal"><b>${x.dish||'食事'}</b><span>${x.kcal==null?'--':Math.round(x.kcal)+' kcal'}</span></div>`).join('');if(a)try{window.SuGNutrition?.setDaily?.(a)}catch(_){}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(render,80),{once:true});else setTimeout(render,80);window.addEventListener('sug:nutrition-analysis',()=>setTimeout(render,0));window.SuGFoodPhoto={VERSION,endpoint,meals,aggregate,analyzeDataUrl,syncNutrition,render};
})();