(()=>{'use strict';
const FLOW_KEY='sug_food_walk_flow_v1';
const $=s=>document.querySelector(s),read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function flow(){const f=read(FLOW_KEY,null),d=new Date().toISOString().slice(0,10);return f?.date===d?f:null}
function startPartner(p){const d=new Date().toISOString().slice(0,10),f={date:d,nutrient:'partner',label:'提携店',query:p.name,startAt:new Date().toISOString(),status:'STORE_SELECTED',storeName:p.name,partnerId:p.id,partnerDiscountYen:p.discountYen,partnerPoints:p.points,partnerCostYen:p.costYen,targetMenu:p.targetMenu||'',partnerAddress:p.address||'',trackedMeters:0,trackPoints:0};write(FLOW_KEY,f);window.SuGPointsV2716?.addAction(`partner-food-walk:${d}:${p.id}`,'提携店へFOOD WALK開始',100,{source:'partnerFoodWalk',partnerId:p.id,store:p.name});window.SuGMicronutritionV2720?.render?.();render();const q=encodeURIComponent([p.name,p.address].filter(Boolean).join(' '));window.open(`https://www.google.com/maps/search/?api=1&query=${q}`,'_blank','noopener')}
function redeem(p){const api=window.SuGPartnersV2722;if(!api)return alert('提携店情報を読み込み中');const r=api.redeemPartner(p.id);if(!r.ok){const msg={POINTS_LOW:'ポイントが足りません',MONTHLY_BUDGET:'今月の運営原資上限です',PARTNER_MONTHLY_LIMIT:'この店の今月利用上限です',PARTNER_NOT_AVAILABLE:'現在この特典は利用できません'}[r.reason]||'交換できません';return alert(msg)}const f=flow();if(f&&f.partnerId===p.id){f.rewardCode=r.redemption.code;f.rewardUsedAt=new Date().toISOString();write(FLOW_KEY,f)}render();alert(`${p.name}\n交換完了\n${r.redemption.code}`)}
function render(){let c=$('#partnerFoodCard');const anchor=$('#microNutritionCard');if(!anchor)return;if(!c){c=document.createElement('section');c.id='partnerFoodCard';c.className='card';anchor.after(c)}const api=window.SuGPartnersV2722,ps=api?.eligible?.('FOOD')||[],f=flow();c.innerHTML=`<div class="ey">PARTNER FOOD · V27.22</div><h2>提携店を優先して食べに行く</h2><div class="sub">登録済みの有効な提携飲食店だけ表示。未提携店はここには出しません。</div>${ps.length?ps.map(p=>`<div class="pfRow"><div><b>${p.name}</b><span>${p.discountYen?`${p.discountYen}円OFF`:'特典'}｜${p.points}pt${p.monthlyLimit?`｜月${p.monthlyLimit}回まで`:''}</span><small>${p.targetMenu||'対象メニュー未設定'}${p.address?`｜${p.address}`:''}</small></div><div class="pfBtns"><button data-go="${p.id}">この店へWALK</button><button data-redeem="${p.id}" ${p.points<=0?'':' '} >特典交換</button></div></div>`).join(''):'<div class="empty">有効な提携飲食店はまだ登録されていません。</div>'}${f?.partnerId?`<div class="pfActive"><b>選択中：${f.storeName}</b><span>${f.partnerDiscountYen?`${f.partnerDiscountYen}円OFF｜`:''}${f.partnerPoints||0}pt${f.targetMenu?`｜${f.targetMenu}`:''}</span>${f.rewardCode?`<strong>特典コード ${f.rewardCode}</strong>`:''}</div>`:''}`;
let st=$('#pfStyle');if(!st){st=document.createElement('style');st.id='pfStyle';document.head.appendChild(st)}st.textContent=`.pfRow{display:grid;grid-template-columns:1fr auto;gap:10px;padding:13px 0;border-top:1px solid #29292e}.pfRow:first-of-type{margin-top:10px}.pfRow b{display:block;color:#e4c56d}.pfRow span,.pfRow small,.pfActive span{display:block;font-size:10px;color:#85858d;margin-top:4px}.pfBtns button{display:block;width:100%;margin:4px 0;border:1px solid #66542e;background:#17140d;color:#e4c56d;border-radius:10px;padding:8px 10px;font-weight:800}.pfActive{margin-top:12px;border:1px solid #66542e;border-radius:12px;padding:10px}.pfActive strong{display:block;color:#79dfa5;margin-top:7px}@media(max-width:480px){.pfRow{grid-template-columns:1fr}.pfBtns{display:grid;grid-template-columns:1fr 1fr;gap:6px}}`;
c.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{const p=ps.find(x=>x.id===b.dataset.go);if(p)startPartner(p)});c.querySelectorAll('[data-redeem]').forEach(b=>b.onclick=()=>{const p=ps.find(x=>x.id===b.dataset.redeem);if(p)redeem(p)})}
setTimeout(render,420);window.addEventListener('sug:partners-change',render);window.addEventListener('sug:points-change',render);window.SuGPartnerFoodV2722={render,startPartner};
})();