(()=>{'use strict';const V='27.78',K='sug_native_health_v1';
const num=(o,ks)=>{for(const k of ks){const v=o?.[k];if(v!==undefined&&v!==null&&String(v).trim()!==''){const n=Number(String(v).replace(/[,\s]/g,'').replace(/(?:歩|時間|h|hr|hrs|kg|bpm|ms|%|回\/分)$/i,''));if(Number.isFinite(n))return n}}return null};
function loadRuntime(id,src){if(document.getElementById(id))return;const s=document.createElement('script');s.id=id;s.src=src;document.body.appendChild(s)}
function ensureRuntimes(){loadRuntime('sugRecoveryBodyContextV2777','./recovery-body-context-v27.77.js?v=27.78');loadRuntime('sugNutritionRecoveryV2778','./nutrition-recovery-engine-v27.78.js?v=27.78')}
function statusEl(){let el=document.getElementById('healthNativeStatus');if(el)return el;const grid=document.querySelector('.health');if(!grid)return null;el=document.createElement('div');el.id='healthNativeStatus';el.style.cssText='grid-column:1/-1;margin-top:2px;padding:9px 10px;border:1px solid #2c2c31;border-radius:11px;background:#0b0b0d;color:#777;font-size:10px;line-height:1.55';el.textContent='iPhone HealthKit：未受信';grid.appendChild(el);return el}
function fmtTime(v){const d=new Date(v||'');if(Number.isNaN(d.getTime()))return '--';return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
function status(p){const el=statusEl();if(!el)return;const has=v=>v!==undefined&&v!==null&&Number.isFinite(Number(v));const bits=[['歩数',has(p?.steps)||has(p?.stepCount)],['睡眠',has(p?.sleep)||has(p?.sleepHours)],['安静時心拍',has(p?.restingHeartRate)||has(p?.heartRate)],['HRV',has(p?.hrv)||has(p?.hrvMs)],['体重',has(p?.weight)||has(p?.weightKg)]].map(([k,ok])=>`${k}${ok?'✓':'—'}`).join('｜');const src=p?.source==='healthkit_native'?'iPhone HealthKit':p?.source==='apple_health_shortcuts'?'Apple Health':'Health';el.textContent=`${src}同期 ${fmtTime(p?.syncedAt)}｜${bits}`;el.style.color='#d9b85f'}
function parseIncoming(){try{const q=new URLSearchParams(location.search||'');let o=null;const keys=['steps','stepCount','sleep','sleepHours','heart','heartRate','restingHeartRate','weight','weightKg','hrv','hrvMs','sleepEfficiency','readiness','hrvBaseline','rhrBaseline'];if(q.get('sug-health')==='1'||q.get('health')==='1'||keys.some(k=>q.has(k))){o={};q.forEach((v,k)=>o[k]=v)}let h=String(location.hash||'').replace(/^#/,'');if(!o&&/^sug-health(?:[?&=]|$)/.test(h)){if(h.startsWith('sug-health=')){try{o=JSON.parse(decodeURIComponent(h.slice(11)))}catch{}}else{o={};new URLSearchParams(h.replace(/^sug-health[?&]?/,'')).forEach((v,k)=>o[k]=v)}}if(!o)return null;let sleep=num(o,['sleep','sleepHours','sleep_hours','sleepMinutes','sleep_minutes','sleepSeconds','sleep_seconds']);if(sleep!=null&&sleep>1440)sleep/=3600;else if(sleep!=null&&sleep>24)sleep/=60;const p={source:'apple_health_shortcuts',steps:num(o,['steps','stepCount','step_count']),sleep,heartRate:num(o,['heart','heartRate','heart_rate','hr','latestHeartRate']),restingHeartRate:num(o,['restingHeartRate','resting_hr','rhr']),weight:num(o,['weight','weightKg','weight_kg']),hrv:num(o,['hrv','hrvMs','hrv_ms','sdnn']),sleepEfficiency:num(o,['sleepEfficiency','sleep_efficiency','efficiency']),readiness:num(o,['readiness','readinessScore']),hrvBaseline:num(o,['hrvBaseline','hrv_base','hrv28']),rhrBaseline:num(o,['rhrBaseline','restingHeartRateBaseline','rhr_base','rhr28']),syncedAt:new Date().toISOString()};if([p.steps,p.sleep,p.heartRate,p.restingHeartRate,p.weight,p.hrv,p.sleepEfficiency,p.readiness,p.hrvBaseline,p.rhrBaseline].every(v=>v==null))return null;return p}catch{return null}}
function cached(){try{const p=window.__SUG_NATIVE_HEALTH__||JSON.parse(localStorage.getItem(K)||'null');return p&&['healthkit_native','apple_health_shortcuts'].includes(p.source)?p:null}catch{return null}}
function setInput(id,v){if(v==null)return;const el=document.getElementById(id);if(!el)return;el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}))}
function autofill(p){setInput('hrvToday',p?.hrv??p?.hrvMs);setInput('hrvBase',p?.hrvBaseline??p?.hrvBase);setInput('sleepEff',p?.sleepEfficiency);setInput('rhrToday',p?.restingHeartRate??p?.heartRate);setInput('rhrBase',p?.rhrBaseline??p?.restingHeartRateBaseline);setInput('readiness',p?.readiness??p?.readinessScore)}
function apply(p){if(!p)return false;ensureRuntimes();window.__SUG_NATIVE_HEALTH__=p;try{localStorage.setItem(K,JSON.stringify(p))}catch{};status(p);window.dispatchEvent(new CustomEvent('sug:native-health',{detail:p}));window.SuGBody?.receiveNative?.(p);window.SuGV27?.receiveNative?.(p);window.SuGHealthV2?.receiveNative?.(p);window.SuGBodyContext?.receiveHealth?.(p);window.SuGNutrition?.receiveHealth?.(p);autofill(p);return true}
function boot(){ensureRuntimes();statusEl();const p=parseIncoming()||cached();if(p)apply(p)}
boot();document.addEventListener('DOMContentLoaded',boot,{once:true});window.addEventListener('pageshow',boot);window.addEventListener('hashchange',boot);window.addEventListener('sug:native-health',e=>status(e.detail));setTimeout(boot,300);setTimeout(boot,1200);window.SuGBodyHealthBridgeV2778={version:V,boot,apply,parseIncoming,autofill,ensureRuntimes};})();