(()=>{'use strict';
const VERSION='27.82',K='sug_body_ideal_gap_v1',IDEAL='sug_v27_ideal',LOG='sug_body_training_log_v1',DB='sug_body_photos_v1',STORE='photos',PHOTO_KEY='ideal-gap:current',API='https://sug-private-engine.vercel.app/api/body-future-image';
let futureImage='',currentPhoto='';
const read=(k,f=null)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function db(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function photoPut(v){const d=await db();return new Promise((res,rej)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(v,PHOTO_KEY);t.oncomplete=()=>res();t.onerror=()=>rej(t.error)})}
async function photoGet(){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(STORE).objectStore(STORE).get(PHOTO_KEY);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}
const css=`#idealGapCard .igGrid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.igBox{border:1px solid #303037;border-radius:15px;padding:12px;background:#0b0b0d}.igBox img{width:100%;aspect-ratio:3/4;object-fit:cover;border-radius:11px;background:#08080a}.igBtn{width:100%;border:1px solid #806729;background:#d0a43d;color:#111;border-radius:12px;padding:13px;font-weight:900;margin-top:10px}.igGhost{background:#151518;color:#e7c566}.igGap{margin-top:12px;border-top:1px solid #303037;padding-top:12px}.igGap b{color:#efd078}.igInputs{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:10px}.igInputs label{font-size:9px;color:#777}.igInputs input{width:100%;margin-top:5px;background:#101012;color:#fff;border:1px solid #34343a;border-radius:9px;padding:10px}.igMonths{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:10px}.igMonths button{border:1px solid #38383f;background:#17171b;color:#aaa;border-radius:10px;padding:10px;font-weight:900}.igMonths button.on{background:#d0a43d;color:#111}.igFuture{margin-top:12px;border:1px solid #735e2e;border-radius:15px;padding:12px}.igFuture img{width:100%;border-radius:11px;display:none}.igNote{font-size:10px;color:#777;line-height:1.55;margin-top:8px}@media(max-width:480px){#idealGapCard .igGrid{grid-template-columns:1fr}.igInputs{grid-template-columns:1fr}}`;
function mount(){if(document.getElementById('idealGapCard'))return;const ideal=document.getElementById('idealV27Card');if(!ideal)return setTimeout(mount,300);const s=document.createElement('style');s.textContent=css;document.head.appendChild(s);const card=document.createElement('section');card.id='idealGapCard';card.className='card';card.innerHTML=`<div class="ey">CURRENT → IDEAL → FUTURE · V${VERSION}</div><h2>現状と理想のGAP</h2><div class="igGrid"><div class="igBox"><div class="sub">CURRENT｜現在</div><img id="igCurrent"><input id="igPhoto" type="file" accept="image/*" capture="environment" hidden><button id="igShoot" class="igBtn">現状写真を撮る / 選ぶ</button></div><div class="igBox"><div class="sub">IDEAL｜理想</div><div id="igIdeal" class="sub" style="padding:14px 0">理想体型を先に設定</div></div></div><div class="igInputs"><label>現在体脂肪率 %<input id="igCurrentBf" type="number" min="3" max="60" step="0.1" placeholder="実測値を入力"></label><label>筋肉量 kg（任意）<input id="igMuscle" type="number" min="0" max="100" step="0.1" placeholder="測定値があれば"></label></div><div class="igGap"><b id="igGapTitle">GAP判定待ち</b><div id="igGapText" class="sub"></div><div id="igEta" class="sub" style="margin-top:7px"></div></div><div class="sub" style="margin-top:12px">未来画像の表示期間（到達予測とは別）</div><div class="igMonths"><button data-m="1">1か月</button><button data-m="3" class="on">3か月</button><button data-m="6">6か月</button></div><div class="igFuture"><b id="igFutureTitle">3か月後イメージ</b><img id="igFutureImg"><div id="igFutureText" class="sub"></div></div><button id="igGenerate" class="igBtn">AIで未来イメージを生成</button><button id="igSave" class="igBtn igGhost">GAPデータを保存</button><div class="igNote">1・3・6か月は別の変化量ルールで生成します。写真から体脂肪率は推定しません。現在写真は端末内IndexedDBへ保存し、生成画像は保存しません。</div>`;ideal.insertAdjacentElement('afterend',card);bind();loadPhoto().then(render)}
function ideal(){return read(IDEAL,null)}
function healthWeight(){const n=parseFloat(document.getElementById('weight')?.textContent||'');return Number.isFinite(n)&&n>0?n:null}
function idealRange(){const s=String(ideal()?.idealVisionBodyFat||'');const n=(s.match(/\d+(?:\.\d+)?/g)||[]).map(Number).filter(Number.isFinite);if(!n.length)return null;const low=Math.min(...n),high=Math.max(...n);return{low,high,mid:(low+high)/2}}
function trainingPerWeek(){const logs=read(LOG,[]),cut=Date.now()-28*864e5,days=new Set(logs.filter(x=>{const t=Date.parse(x.date||x.at||'');return Number.isFinite(t)&&t>=cut}).map(x=>String(x.date||x.at).slice(0,10)));return days.size/4}
function rateFor(freq){return freq>=3?.8:freq>=2?.6:.4}
function validBf(v){return v!==null&&v!==''&&Number.isFinite(Number(v))&&Number(v)>=3&&Number(v)<=60?Number(v):null}
function validMuscle(v){return v!==null&&v!==''&&Number.isFinite(Number(v))&&Number(v)>0?Number(v):null}
function captureInputs(v){const bf=validBf(document.getElementById('igCurrentBf')?.value),muscle=validMuscle(document.getElementById('igMuscle')?.value);v.currentBodyFat=bf;v.muscleKg=muscle;return v}
function eta(){const v=read(K,{}),cur=validBf(v.currentBodyFat),r=idealRange();if(cur===null||!r)return null;let gap=0,target=cur;if(cur>r.high){gap=cur-r.high;target=r.high}else if(cur<r.low){gap=r.low-cur;target=r.low}const freq=trainingPerWeek(),rate=rateFor(freq);return{months:gap<.1?0:Math.max(1,Math.ceil(gap/rate)),gap,target,freq,rate,range:r}}
function visualTargets(months){return months===1?{level:1,label:'subtle',shoulders:3,chest:2,arms:2,back:2,legs:1,waist:2}:months===6?{level:5,label:'strong',shoulders:15,chest:13,arms:13,back:14,legs:9,waist:9}:{level:3,label:'clear',shoulders:9,chest:8,arms:8,back:9,legs:5,waist:5}}
function transformationPlan(months){const v=captureInputs(read(K,{month:3})),cur=validBf(v.currentBodyFat),r=idealRange(),freq=trainingPerWeek(),rate=rateFor(freq),shape=visualTargets(months);let projected=null,delta=null,target=null;if(cur!==null&&r){if(cur>r.high){target=r.high;projected=Math.max(target,cur-rate*months)}else if(cur<r.low){target=r.low;projected=Math.min(target,cur+rate*months)}else{target=cur;projected=cur}delta=Number((projected-cur).toFixed(1));projected=Number(projected.toFixed(1))}return{ruleVersion:'27.82',months,currentBodyFat:cur,idealBodyFatLow:r?.low??null,idealBodyFatHigh:r?.high??null,targetBodyFat:target,projectedBodyFat:projected,plannedBodyFatChange:delta,trainingDaysPerWeek:Number(freq.toFixed(1)),ruleRatePtPerMonth:rate,muscleKg:validMuscle(v.muscleKg),visualTargets:shape}}
function gapText(){const i=ideal(),w=healthWeight(),v=read(K,{});if(!i)return'理想体型が未設定です。';let a=`理想：${i.idealVisionName||i.idealVisionType||'未設定'} / 体脂肪 ${i.idealVisionBodyFat||'--'}`;if(w)a+=`。現在体重 ${w.toFixed(1)}kg。`;const bf=validBf(v.currentBodyFat),muscle=validMuscle(v.muscleKg);if(bf!==null)a+=` 現在体脂肪 ${bf.toFixed(1)}%。`;if(muscle!==null)a+=` 筋肉量 ${muscle.toFixed(1)}kg。`;return a+' 写真そのものから数値は推定しません。'}
function compress(file,max=1280,q=.82){return new Promise((resolve,reject)=>{const u=URL.createObjectURL(file),im=new Image();im.onload=()=>{try{const scale=Math.min(1,max/Math.max(im.naturalWidth,im.naturalHeight)),w=Math.max(1,Math.round(im.naturalWidth*scale)),h=Math.max(1,Math.round(im.naturalHeight*scale)),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);URL.revokeObjectURL(u);c.toBlob(b=>b?resolve(b):reject(new Error('PHOTO_COMPRESS_FAILED')),'image/jpeg',q)}catch(e){URL.revokeObjectURL(u);reject(e)}};im.onerror=()=>{URL.revokeObjectURL(u);reject(new Error('PHOTO_READ_FAILED'))};im.src=u})}
function blobDataUrl(blob){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(blob)})}
function apiPhoto(){return new Promise((resolve,reject)=>{if(!currentPhoto)return reject(new Error('NO_PHOTO'));const im=new Image();im.onload=()=>{try{const max=720,scale=Math.min(1,max/Math.max(im.naturalWidth,im.naturalHeight)),w=Math.max(1,Math.round(im.naturalWidth*scale)),h=Math.max(1,Math.round(im.naturalHeight*scale)),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);resolve(c.toDataURL('image/jpeg',.58))}catch(e){reject(e)}};im.onerror=()=>reject(new Error('PHOTO_API_COMPRESS_FAILED'));im.src=currentPhoto})}
async function loadPhoto(){try{const old=read(K,{}),blob=await photoGet();if(blob)currentPhoto=await blobDataUrl(blob);else if(old.currentPhoto){currentPhoto=old.currentPhoto;const r=await fetch(old.currentPhoto),b=await r.blob();await photoPut(b);delete old.currentPhoto;write(K,old)}}catch{currentPhoto=''}}
async function generate(){const v=captureInputs(read(K,{month:3})),i=ideal();write(K,v);if(!currentPhoto)return alert('先に現状写真を撮ってください');if(!i)return alert('先に理想体型を設定してください');const months=v.month||3,plan=transformationPlan(months),btn=document.getElementById('igGenerate'),txt=document.getElementById('igFutureText');btn.disabled=true;txt.textContent='AI生成中…';try{const imageDataUrl=await apiPhoto();if(imageDataUrl.length>900000)throw new Error('PHOTO_TOO_LARGE');const payload={imageDataUrl,months,ideal:i.idealVisionName||i.idealVisionType||'FITNESS',bodyFat:i.idealVisionBodyFat||'',...plan};const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b.error||`HTTP ${r.status}`);futureImage=b.imageDataUrl||b.imageUrl||'';v.futureGeneratedAt=b.generatedAt||new Date().toISOString();v.futureMonths=months;v.lastPlan=plan;delete v.futureImage;delete v.currentPhoto;write(K,v);render()}catch(e){console.error('future-image',e);txt.textContent='未来画像を生成できませんでした。もう一度お試しください。'}finally{btn.disabled=false}}
function bind(){const input=document.getElementById('igPhoto');document.getElementById('igShoot').onclick=()=>input.click();input.onchange=async()=>{const f=input.files?.[0];if(!f)return;try{const blob=await compress(f),v=read(K,{month:3});await photoPut(blob);currentPhoto=await blobDataUrl(blob);v.photoAt=new Date().toISOString();delete v.currentPhoto;futureImage='';write(K,v);render()}catch{alert('写真を読み込めませんでした')}};document.querySelectorAll('#idealGapCard [data-m]').forEach(b=>b.onclick=()=>{const v=read(K,{month:3});v.month=+b.dataset.m;futureImage='';write(K,v);render()});document.getElementById('igGenerate').onclick=generate;document.getElementById('igSave').onclick=()=>{const v=captureInputs(read(K,{month:3}));v.savedAt=new Date().toISOString();v.ideal=ideal();v.weight=healthWeight();delete v.currentPhoto;write(K,v);render()};window.addEventListener('sug:ideal-change',render)}
function render(){const v=read(K,{month:3}),i=ideal(),cur=document.getElementById('igCurrent');if(!cur)return;if(currentPhoto){cur.src=currentPhoto;cur.style.display='block'}else cur.style.display='none';document.getElementById('igCurrentBf').value=validBf(v.currentBodyFat)??'';document.getElementById('igMuscle').value=validMuscle(v.muscleKg)??'';document.getElementById('igIdeal').innerHTML=i?`<b style="color:#efd078;font-size:18px">${i.idealVisionName||i.idealVisionType}</b><br>体脂肪 ${i.idealVisionBodyFat||'--'}`:'理想体型を先に設定';document.getElementById('igGapTitle').textContent=currentPhoto&&i?'GAP基準を作成済み':'GAP判定待ち';document.getElementById('igGapText').textContent=gapText();const e=eta();document.getElementById('igEta').textContent=e?e.months===0?'到達目安：現在体脂肪率は理想レンジ内です。':`到達目安：約${e.months}か月｜理想レンジまで ${e.gap.toFixed(1)}pt｜直近トレ ${e.freq.toFixed(1)}日/週。固定ルールによる目安です。`:'到達月：算出不可｜現在体脂肪率と理想体脂肪レンジが必要です。';document.querySelectorAll('#idealGapCard [data-m]').forEach(b=>b.classList.toggle('on',+b.dataset.m===(v.month||3)));const months=v.month||3,shape=visualTargets(months);document.getElementById('igFutureTitle').textContent=`${months}か月後イメージ`;const img=document.getElementById('igFutureImg');if(futureImage&&v.futureMonths===months){img.src=futureImage;img.style.display='block';document.getElementById('igFutureText').textContent=`AI生成済み｜変化レベル ${shape.level}/5 ${v.futureGeneratedAt?new Date(v.futureGeneratedAt).toLocaleString('ja-JP'):''}`}else{img.style.display='none';document.getElementById('igFutureText').textContent=currentPhoto&&i?`${months}か月ルール：変化レベル ${shape.level}/5。1・3・6か月で別の身体変化量を使います。`:'現在写真と理想体型を設定してください。'}}
mount();window.SuGIdealGapV2765={mount,render,generate,eta,transformationPlan,read:()=>read(K,null),endpoint:API};
})();
