(()=>{'use strict';
const V='0.1.0',DAILY='sug_body_lite_daily_v1',PREF='sug_body_lite_pref_v1',WATCH='sug_body_lite_watch_v1';
const $=s=>document.querySelector(s),n=v=>Number.isFinite(Number(v))?Number(v):null,j=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}};
function localRow(){const daily=j(DAILY,[]),pref=j(PREF,{mode:'community'}),watch=j(WATCH,{}),latest=daily[0]||{};return {memberId:'THIS-DEVICE',displayName:'この端末',mode:pref.mode||latest.mode||'community',latest,daily,watch}}
function avg(xs,key){const vs=xs.map(x=>key.split('.').reduce((o,k)=>o?.[k],x)).map(n).filter(v=>v!=null);return vs.length?vs.reduce((a,b)=>a+b,0)/vs.length:null}
function rowStats(row){const xs=Array.isArray(row.daily)?row.daily:[],latest=row.latest||xs[0]||{},lastAt=n(row.watch?.lastActivityAt)||Date.parse(latest.syncedAt||'')||null,lastDays=lastAt?Math.max(0,(Date.now()-lastAt)/86400000):null,pain=n(latest.condition?.pain),steps=n(latest.health?.steps),questDays=xs.filter(x=>x.quest?.participated).length,outsideDays=xs.filter(x=>x.watch?.locationRecorded||n(x.quest?.routeCount)>0).length;let status='GOOD',reason='継続';if(lastDays!=null&&lastDays>=3){status='CHECK';reason='3日以上活動更新なし'}if(pain!=null&&pain>=4){status='ALERT';reason='痛み4以上'}if(steps!=null&&steps<1000&&xs.length>=2&&status==='GOOD'){status='WATCH';reason='活動量低下'}return {...row,stats:{days:xs.length,avgSteps:avg(xs,'health.steps'),avgSleep:avg(xs,'health.sleepHours'),questDays,outsideDays,pain,steps,lastAt,lastDays,status,reason}}}
let rows=[localRow()];
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmt(v,d=0){return v==null?'--':Number(v).toFixed(d)}
function render(){const out=rows.map(rowStats),alert=out.filter(x=>x.stats.status==='ALERT').length,check=out.filter(x=>['CHECK','WATCH'].includes(x.stats.status)).length,total=out.length;$('#adminTotal').textContent=total;$('#adminAlert').textContent=alert;$('#adminCheck').textContent=check;$('#adminQuest').textContent=out.reduce((a,x)=>a+x.stats.questDays,0);$('#memberRows').innerHTML=out.map(x=>`<div class="member ${x.stats.status.toLowerCase()}"><div><b>${esc(x.displayName||x.memberId)}</b><small>${esc(String(x.mode||'').toUpperCase())}｜${esc(x.stats.reason)}</small></div><div class="mini"><span>歩数<b>${x.stats.steps==null?'--':Math.round(x.stats.steps).toLocaleString()}</b></span><span>平均<b>${x.stats.avgSteps==null?'--':Math.round(x.stats.avgSteps).toLocaleString()}</b></span><span>QUEST<b>${x.stats.questDays}日</b></span><span>外出<b>${x.stats.outsideDays}日</b></span><span>痛み<b>${x.stats.pain??'--'}</b></span></div><div class="last">最終活動：${x.stats.lastAt?new Date(x.stats.lastAt).toLocaleString('ja-JP'):'--'}</div></div>`).join('')||'<div class="empty">データなし</div>'}
function setRows(next){rows=Array.isArray(next)?next:[];render()}
function boot(){render();window.addEventListener('storage',e=>{if([DAILY,PREF,WATCH].includes(e.key)){rows=[localRow()];render()}});setInterval(()=>{if(rows.length===1&&rows[0].memberId==='THIS-DEVICE'){rows=[localRow()];render()}},10000)}
window.SuGBodyLiteAdmin={version:V,setRows,rowStats,render,localRow};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();