(()=>{'use strict';
const KEY='sug_body_micronutrition_v1',PHOTO_KEY='sug_body_food_photo_v1',FLOW_KEY='sug_food_walk_flow_v1';
const $=s=>document.querySelector(s),read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const day=()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
const targets={iron:{label:'鉄',unit:'mg',target:8,foods:['赤身肉','レバー','あさり','かつお','まぐろ','小松菜']},magnesium:{label:'Mg',unit:'mg',target:340,foods:['納豆','豆腐','海藻','そば','アーモンド','魚']},zinc:{label:'亜鉛',unit:'mg',target:11,foods:['牡蠣','赤身肉','卵','チーズ','納豆']},calcium:{label:'Ca',unit:'mg',target:750,foods:['小魚','ヨーグルト','豆腐','小松菜','牛乳']},potassium:{label:'K',unit:'mg',target:3000,foods:['芋','海藻','豆類','バナナ','野菜','魚']},fiber:{label:'食物繊維',unit:'g',target:22,foods:['豆類','野菜','海藻','きのこ','玄米','オートミール']},omega3:{label:'EPA/DHA',unit:'g',target:1.0,foods:['さば','いわし','さんま','鮭','まぐろ']}};
const mapQueries={iron:'赤身肉 あさり かつお 定食',magnesium:'そば 豆腐 納豆 和食',zinc:'牡蠣 赤身肉 卵 定食',calcium:'小魚 豆腐 小松菜 定食',potassium:'野菜 海藻 芋 定食',fiber:'玄米 野菜 豆 海藻 定食',omega3:'さば いわし 鮭 定食'};
function rows(){return read(KEY,[])} function todayRow(){return rows().find(x=>x.date===day())||{date:day()}}
function score(row){return Object.entries(targets).map(([k,t])=>{const v=Number(row[k]||0),ratio=v/t.target;return{k,...t,value:v,ratio,gap:Math.max(0,t.target-v)}}).sort((a,b)=>a.ratio-b.ratio)}
function flow(){const f=read(FLOW_KEY,null);return f?.date===day()?f:null}
function locate(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('GEO_UNAVAILABLE'));navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy}),reject,{enableHighAccuracy:true,timeout:10000,maximumAge:60000})})}
function searchUrl(q,loc){const query=encodeURIComponent(q);return loc?`https://www.google.com/maps/search/?api=1&query=${query}&center=${loc.lat},${loc.lng}`:`https://www.google.com/maps/search/?api=1&query=${query}`}
async function startWalk(k){const t=targets[k],q=mapQueries[k];let loc=null;try{loc=await locate()}catch{}const f={date:day(),nutrient:k,label:t.label,query:q,startAt:new Date().toISOString(),start:loc,status:'SEARCHING'};write(FLOW_KEY,f);window.SuGPointsV2716?.addAction(`nutrition:walk-start:${day()}:${k}`,`${t.label}を補う食事へ歩く`,100,{source:'nutritionWalk',nutrient:k});render();window.open(searchUrl(q,loc),'_blank','noopener')}
function photoStore(file){if(!file)return;const r=new FileReader();r.onload=()=>{write(PHOTO_KEY,{date:day(),name:file.name,type:file.type,data:r.result,at:new Date().toISOString()});const f=flow();if(f){f.status='MEAL_PHOTO';f.mealPhotoAt=new Date().toISOString();write(FLOW_KEY,f);window.SuGPointsV2716?.addAction(`nutrition:meal-photo:${day()}:${f.nutrient}`,'食後写真を記録',100,{source:'nutritionMeal',nutrient:f.nutrient})}render()};r.readAsDataURL(file)}
function finishFlow(){const f=flow();if(!f)return;f.status='DONE';f.completedAt=new Date().toISOString();write(FLOW_KEY,f);window.SuGPointsV2716?.addAction(`nutrition:food-flow-done:${day()}:${f.nutrient}`,'不足栄養→WALK→食事を完了',200,{source:'nutritionFlow',nutrient:f.nutrient});render()}
function render(){let c=$('#microNutritionCard');if(!c){const a=$('#nutritionWeightCard');if(!a)return;c=document.createElement('section');c.id='microNutritionCard';c.className='card';a.after(c)}const row=todayRow(),sc=score(row),low=sc.slice(0,3),photo=read(PHOTO_KEY,null),f=flow();c.innerHTML=`<div class="ey">MICRONUTRITION · V27.19</div><h2>不足栄養 → 店を探す → WALK → 食べる</h2><div class="sub">食事写真は記録のみ。画像AIは未接続。店舗は固定表示せず、現在地からGoogle Mapsの実在店舗検索へ渡します。</div><div class="mnPhoto"><label class="savebtn" style="display:block;text-align:center;cursor:pointer">食事写真を撮る / 選ぶ<input id="mnPhoto" type="file" accept="image/*" capture="environment" hidden></label>${photo?.date===day()?`<div class="mnThumb"><img src="${photo.data}" alt="今日の食事"><span>今日の食事写真を保存済み</span></div>`:''}</div><div class="mnGrid">${Object.entries(targets).map(([k,t])=>`<label>${t.label} <small>${t.unit}</small><input id="mn_${k}" type="number" step="0.1" min="0" value="${row[k]??''}" placeholder="目安 ${t.target}"></label>`).join('')}</div><button id="mnSave" class="savebtn">今日の微量栄養を保存</button>${f?`<div class="mnFlow"><b>ACTIVE FOOD WALK</b><strong>${f.label}を補う店を探す</strong><span>${f.status==='DONE'?'完了':f.status==='MEAL_PHOTO'?'食後写真まで完了':'店舗検索/WALK中'}</span><small>${f.startAt?new Date(f.startAt).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'}):''}${f.start?'｜位置取得済み':''}</small>${f.status==='MEAL_PHOTO'?'<button id="mnFinish">食事完了にする</button>':''}</div>`:''}<div class="mnAdvice"><b>不足優先 TOP3</b>${low.map((x,i)=>`<div class="mnNeed"><strong>${i+1}. ${x.label}</strong><span>${x.value||0}${x.unit} / 目安 ${x.target}${x.unit}</span><small>候補：${x.foods.slice(0,4).join('・')}</small><button data-walk="${x.k}">現在地から店を探してWALK開始</button><button data-reward="meal100">飲食100円OFFを見る</button></div>`).join('')}</div><div class="sub" style="margin-top:10px">※目安値は一般的な成人向け初期値。店舗の営業・メニュー・在庫はGoogle Maps側の最新情報を確認。位置情報は端末内のWALK開始記録にのみ保存。</div>`;
const st=document.getElementById('mnStyle')||document.createElement('style');st.id='mnStyle';st.textContent=`#microNutritionCard .mnGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:14px}.mnGrid label{font-size:9px;color:#777}.mnGrid input{width:100%;margin-top:4px;background:#0b0b0d;color:#fff;border:1px solid #34343b;border-radius:10px;padding:10px}.mnNeed{border-top:1px solid #29292e;padding:12px 0}.mnNeed strong{display:block;color:#e4c56d}.mnNeed span,.mnNeed small,.mnFlow span,.mnFlow small{display:block;font-size:10px;color:#85858d;margin-top:4px}.mnNeed button,.mnFlow button{margin:8px 6px 0 0;border:1px solid #66542e;background:#17140d;color:#e4c56d;border-radius:10px;padding:8px 10px;font-weight:800}.mnThumb{display:flex;align-items:center;gap:10px;margin-top:10px}.mnThumb img{width:72px;height:72px;object-fit:cover;border-radius:12px;border:1px solid #34343b}.mnThumb span{font-size:10px;color:#85858d}.mnFlow{margin-top:14px;border:1px solid #66542e;background:#15130d;border-radius:14px;padding:12px}.mnFlow b{font-size:9px;color:#d9b85f;letter-spacing:.12em}.mnFlow strong{display:block;margin-top:4px}@media(max-width:480px){#microNutritionCard .mnGrid{grid-template-columns:1fr 1fr}}`;if(!st.parentNode)document.head.appendChild(st);
$('#mnPhoto').onchange=e=>photoStore(e.target.files?.[0]);$('#mnSave').onclick=()=>{const r={date:day()};Object.keys(targets).forEach(k=>r[k]=Number($('#mn_'+k).value)||0);const xs=rows().filter(x=>x.date!==r.date);xs.push(r);write(KEY,xs.slice(-120));window.dispatchEvent(new CustomEvent('sug:micronutrition',{detail:r}));window.SuGPointsV2716?.addAction(`nutrition:micro:${day()}`,'微量栄養を記録',100,{source:'micronutrition'});render()};c.querySelectorAll('[data-walk]').forEach(b=>b.onclick=()=>startWalk(b.dataset.walk));c.querySelectorAll('[data-reward]').forEach(b=>b.onclick=()=>{const r=window.SuGRewardsV2717?.catalog?.().find(x=>x.id===b.dataset.reward);alert(r?`${r.name}\n必要 ${r.points}pt`:'交換所を読み込み中')});const fin=$('#mnFinish');if(fin)fin.onclick=finishFlow}
setTimeout(render,260);window.addEventListener('sug:nutrition-weight',render);window.SuGMicronutritionV2719={render,rows,score,targets,flow,startWalk};
})();