(()=>{'use strict';
const KEY='sug_body_micronutrition_v1',PHOTO_KEY='sug_body_food_photo_v1',FLOW_KEY='sug_food_walk_flow_v1';
const $=s=>document.querySelector(s),read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const day=()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
const targets={iron:{label:'鉄',unit:'mg',target:8,foods:['赤身肉','レバー','あさり','かつお','まぐろ','小松菜']},magnesium:{label:'Mg',unit:'mg',target:340,foods:['納豆','豆腐','海藻','そば','アーモンド','魚']},zinc:{label:'亜鉛',unit:'mg',target:11,foods:['牡蠣','赤身肉','卵','チーズ','納豆']},calcium:{label:'Ca',unit:'mg',target:750,foods:['小魚','ヨーグルト','豆腐','小松菜','牛乳']},potassium:{label:'K',unit:'mg',target:3000,foods:['芋','海藻','豆類','バナナ','野菜','魚']},fiber:{label:'食物繊維',unit:'g',target:22,foods:['豆類','野菜','海藻','きのこ','玄米','オートミール']},omega3:{label:'EPA/DHA',unit:'g',target:1.0,foods:['さば','いわし','さんま','鮭','まぐろ']}};
const mapQueries={iron:'赤身肉 あさり かつお 定食',magnesium:'そば 豆腐 納豆 和食',zinc:'牡蠣 赤身肉 卵 定食',calcium:'小魚 豆腐 小松菜 定食',potassium:'野菜 海藻 芋 定食',fiber:'玄米 野菜 豆 海藻 定食',omega3:'さば いわし 鮭 定食'};
let watchId=null,lastTrackPoint=null;
function rows(){return read(KEY,[])} function todayRow(){return rows().find(x=>x.date===day())||{date:day()}}
function score(row){return Object.entries(targets).map(([k,t])=>{const v=Number(row[k]||0),ratio=v/t.target;return{k,...t,value:v,ratio,gap:Math.max(0,t.target-v)}}).sort((a,b)=>a.ratio-b.ratio)}
function flow(){const f=read(FLOW_KEY,null);return f?.date===day()?f:null}
function saveFlow(f){write(FLOW_KEY,f);return f}
function locate(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('GEO_UNAVAILABLE'));navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,at:new Date().toISOString()}),reject,{enableHighAccuracy:true,timeout:12000,maximumAge:15000})})}
function hav(a,b){if(!a||!b)return 0;const R=6371000,toRad=x=>x*Math.PI/180,dLat=toRad(b.lat-a.lat),dLon=toRad(b.lng-a.lng),la1=toRad(a.lat),la2=toRad(b.lat);const h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.min(1,Math.sqrt(h)))}
function searchUrl(q,loc){const query=encodeURIComponent(q);return loc?`https://www.google.com/maps/search/?api=1&query=${query}&center=${loc.lat},${loc.lng}`:`https://www.google.com/maps/search/?api=1&query=${query}`}
async function startSearch(k){const t=targets[k],q=mapQueries[k];let loc=null;try{loc=await locate()}catch{}const f={date:day(),nutrient:k,label:t.label,query:q,startAt:new Date().toISOString(),start:loc,status:'SEARCHING',storeName:'',trackedMeters:0,trackPoints:0};saveFlow(f);window.SuGPointsV2716?.addAction(`nutrition:walk-start:${day()}:${k}`,`${t.label}を補う食事へ歩く`,100,{source:'nutritionWalk',nutrient:k});render();window.open(searchUrl(q,loc),'_blank','noopener')}
function chooseStore(){const f=flow();if(!f)return;const name=String($('#mnStore')?.value||'').trim();if(!name)return alert('店名を入力してください');f.storeName=name;f.storeChosenAt=new Date().toISOString();f.status='STORE_SELECTED';saveFlow(f);render()}
async function startTracking(){const f=flow();if(!f||!f.storeName)return alert('先に店を決めてください');if(!navigator.geolocation)return alert('位置情報が使えません');if(watchId!=null)return;let start=f.walkStart||null;try{start=await locate()}catch{}f.walkStart=start||f.start;f.walkStartedAt=new Date().toISOString();f.status='WALKING';f.trackedMeters=Number(f.trackedMeters||0);f.trackPoints=Number(f.trackPoints||0);saveFlow(f);lastTrackPoint=f.walkStart;watchId=navigator.geolocation.watchPosition(p=>{const pt={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,at:new Date().toISOString()};const cur=flow();if(!cur)return;if(pt.accuracy<=100&&lastTrackPoint){const d=hav(lastTrackPoint,pt);if(d>=3&&d<=200)cur.trackedMeters=Number(cur.trackedMeters||0)+d}lastTrackPoint=pt;cur.lastPoint=pt;cur.trackPoints=Number(cur.trackPoints||0)+1;saveFlow(cur);const dist=$('#mnDistance');if(dist)dist.textContent=(cur.trackedMeters/1000).toFixed(2)+'km';},()=>{}, {enableHighAccuracy:true,maximumAge:5000,timeout:15000});render()}
function stopTracking(){if(watchId!=null){navigator.geolocation.clearWatch(watchId);watchId=null}lastTrackPoint=null}
async function checkIn(){const f=flow();if(!f)return;let loc=null;try{loc=await locate()}catch{return alert('現在地を取得できませんでした')};stopTracking();f.arrival=loc;f.arrivedAt=new Date().toISOString();f.status='CHECKED_IN';f.straightMeters=hav(f.walkStart||f.start,loc);f.durationMin=f.walkStartedAt?Math.max(1,Math.round((Date.now()-new Date(f.walkStartedAt).getTime())/60000)):null;saveFlow(f);window.SuGPointsV2716?.addAction(`nutrition:checkin:${day()}:${f.nutrient}:${f.storeName}`,'店に到着・チェックイン',100,{source:'nutritionCheckin',nutrient:f.nutrient,store:f.storeName,distanceMeters:Math.round(f.trackedMeters||f.straightMeters||0)});render()}
function photoStore(file){if(!file)return;const r=new FileReader();r.onload=()=>{write(PHOTO_KEY,{date:day(),name:file.name,type:file.type,data:r.result,at:new Date().toISOString()});const f=flow();if(f){f.mealPhotoAt=new Date().toISOString();if(f.status==='CHECKED_IN'||f.status==='WALKING'||f.status==='STORE_SELECTED')f.status='MEAL_PHOTO';saveFlow(f);window.SuGPointsV2716?.addAction(`nutrition:meal-photo:${day()}:${f.nutrient}`,'食事写真を記録',100,{source:'nutritionMeal',nutrient:f.nutrient,store:f.storeName||''})}render()};r.readAsDataURL(file)}
function redeemMeal(){const f=flow();if(!f?.storeName)return alert('先に利用する店を決めてください');const api=window.SuGRewardsV2717;if(!api)return alert('交換所を読み込み中');const r=api.redeem('meal100');if(!r.ok){const msg={POINTS_LOW:'ポイントが足りません',MONTHLY_BUDGET:'今月の運営原資上限です'}[r.reason]||'交換できません';return alert(msg)}f.rewardCode=r.redemption.code;f.rewardUsedAt=new Date().toISOString();saveFlow(f);render()}
function finishFlow(){const f=flow();if(!f)return;if(!f.arrival)return alert('店でチェックインしてください');if(!f.mealPhotoAt)return alert('食事写真を記録してください');f.status='DONE';f.completedAt=new Date().toISOString();saveFlow(f);window.SuGPointsV2716?.addAction(`nutrition:food-flow-done:${day()}:${f.nutrient}`,'不足栄養→WALK→食事を完了',200,{source:'nutritionFlow',nutrient:f.nutrient,store:f.storeName||'',distanceMeters:Math.round(f.trackedMeters||f.straightMeters||0)});render()}
function render(){let c=$('#microNutritionCard');if(!c){const a=$('#nutritionWeightCard');if(!a)return;c=document.createElement('section');c.id='microNutritionCard';c.className='card';a.after(c)}const row=todayRow(),sc=score(row),low=sc.slice(0,3),photo=read(PHOTO_KEY,null),f=flow(),dist=f?Number(f.trackedMeters||f.straightMeters||0):0;c.innerHTML=`<div class="ey">MICRONUTRITION · V27.20</div><h2>不足栄養 → 店 → WALK → CHECK-IN → 食事</h2><div class="sub">Google Mapsで実在店舗を探し、選んだ店名を記録。WALK中はこの画面を開いたままならGPS移動距離を積算します。バックグラウンド計測は未対応です。</div><div class="mnPhoto"><label class="savebtn" style="display:block;text-align:center;cursor:pointer">食事写真を撮る / 選ぶ<input id="mnPhoto" type="file" accept="image/*" capture="environment" hidden></label>${photo?.date===day()?`<div class="mnThumb"><img src="${photo.data}" alt="今日の食事"><span>今日の食事写真を保存済み</span></div>`:''}</div><div class="mnGrid">${Object.entries(targets).map(([k,t])=>`<label>${t.label} <small>${t.unit}</small><input id="mn_${k}" type="number" step="0.1" min="0" value="${row[k]??''}" placeholder="目安 ${t.target}"></label>`).join('')}</div><button id="mnSave" class="savebtn">今日の微量栄養を保存</button>${f?`<div class="mnFlow"><b>ACTIVE FOOD WALK</b><strong>${f.label}｜${f.storeName||'店未選択'}</strong><span>${f.status}</span><small>移動 <span id="mnDistance">${(dist/1000).toFixed(2)}km</span>${f.durationMin?`｜${f.durationMin}分`:''}</small>${!f.storeName?`<div class="mnStore"><input id="mnStore" placeholder="Google Mapsで決めた店名"><button id="mnChooseStore">この店に決める</button></div>`:''}${f.storeName&&['STORE_SELECTED','SEARCHING'].includes(f.status)?'<button id="mnTrack">WALK計測開始</button>':''}${f.status==='WALKING'?'<button id="mnCheckin">店に着いた｜CHECK-IN</button>':''}${f.arrival?'<div class="mnOk">✓ CHECK-IN済み</div>':''}${f.storeName?'<button id="mnReward">提携飲食100円OFFを交換</button>':''}${f.rewardCode?`<div class="mnCode">割引コード <b>${f.rewardCode}</b></div>`:''}${f.arrival&&f.mealPhotoAt&&f.status!=='DONE'?'<button id="mnFinish">食事完了にする</button>':''}${f.status==='DONE'?'<div class="mnOk">✓ FOOD WALK COMPLETE</div>':''}</div>`:''}<div class="mnAdvice"><b>不足優先 TOP3</b>${low.map((x,i)=>`<div class="mnNeed"><strong>${i+1}. ${x.label}</strong><span>${x.value||0}${x.unit} / 目安 ${x.target}${x.unit}</span><small>候補：${x.foods.slice(0,4).join('・')}</small><button data-walk="${x.k}">現在地から店を探す</button></div>`).join('')}</div><div class="sub" style="margin-top:10px">※店舗の営業・メニュー・在庫はGoogle Maps側で確認。GPS距離は端末測位による概算。提携割引は提携店でのみ利用する前提です。</div>`;
const st=document.getElementById('mnStyle')||document.createElement('style');st.id='mnStyle';st.textContent=`#microNutritionCard .mnGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:14px}.mnGrid label{font-size:9px;color:#777}.mnGrid input,.mnStore input{width:100%;margin-top:4px;background:#0b0b0d;color:#fff;border:1px solid #34343b;border-radius:10px;padding:10px}.mnNeed{border-top:1px solid #29292e;padding:12px 0}.mnNeed strong{display:block;color:#e4c56d}.mnNeed span,.mnNeed small,.mnFlow span,.mnFlow small{display:block;font-size:10px;color:#85858d;margin-top:4px}.mnNeed button,.mnFlow button{margin:8px 6px 0 0;border:1px solid #66542e;background:#17140d;color:#e4c56d;border-radius:10px;padding:8px 10px;font-weight:800}.mnThumb{display:flex;align-items:center;gap:10px;margin-top:10px}.mnThumb img{width:72px;height:72px;object-fit:cover;border-radius:12px;border:1px solid #34343b}.mnThumb span{font-size:10px;color:#85858d}.mnFlow{margin-top:14px;border:1px solid #66542e;background:#15130d;border-radius:14px;padding:12px}.mnFlow b{font-size:9px;color:#d9b85f;letter-spacing:.12em}.mnFlow strong{display:block;margin-top:4px}.mnStore{display:grid;grid-template-columns:1fr auto;gap:6px;margin-top:8px}.mnOk{margin-top:8px;color:#79dfa5;font-size:11px;font-weight:900}.mnCode{margin-top:8px;border:1px dashed #8b7136;padding:8px;border-radius:10px;font-size:10px}.mnCode b{display:block;font-size:14px;color:#e4c56d;margin-top:4px}@media(max-width:480px){#microNutritionCard .mnGrid{grid-template-columns:1fr 1fr}.mnStore{grid-template-columns:1fr}}`;if(!st.parentNode)document.head.appendChild(st);
$('#mnPhoto').onchange=e=>photoStore(e.target.files?.[0]);$('#mnSave').onclick=()=>{const r={date:day()};Object.keys(targets).forEach(k=>r[k]=Number($('#mn_'+k).value)||0);const xs=rows().filter(x=>x.date!==r.date);xs.push(r);write(KEY,xs.slice(-120));window.dispatchEvent(new CustomEvent('sug:micronutrition',{detail:r}));window.SuGPointsV2716?.addAction(`nutrition:micro:${day()}`,'微量栄養を記録',100,{source:'micronutrition'});render()};c.querySelectorAll('[data-walk]').forEach(b=>b.onclick=()=>startSearch(b.dataset.walk));const cs=$('#mnChooseStore');if(cs)cs.onclick=chooseStore;const tr=$('#mnTrack');if(tr)tr.onclick=startTracking;const ci=$('#mnCheckin');if(ci)ci.onclick=checkIn;const rw=$('#mnReward');if(rw)rw.onclick=redeemMeal;const fin=$('#mnFinish');if(fin)fin.onclick=finishFlow}
setTimeout(render,260);window.addEventListener('sug:nutrition-weight',render);window.addEventListener('beforeunload',stopTracking);window.SuGMicronutritionV2720={render,rows,score,targets,flow,startSearch,startTracking,checkIn};
})();