(()=>{
  'use strict';
  const VERSION='27.81';
  const DB='sug_body_photos_v1';
  const STORE='photos';
  const HISTORY='sug_body_miss_assessment_v1';
  const TODAY='sug_body_miss_today_v1';
  const BODY_KEY='sug_beauty_body_v1';
  const isMiss=()=>/BEST OF MISS/i.test(document.title||'')||/BEST OF MISS/i.test(document.querySelector('.brandtext span')?.textContent||'');
  if(!isMiss()||document.getElementById('missOfIntegratedEntry'))return;
  const $=id=>document.getElementById(id);
  const nowDate=()=>new Date().toISOString().slice(0,10);
  const safeJson=(raw,fallback)=>{try{return JSON.parse(raw)??fallback}catch{return fallback}};
  const history=()=>safeJson(localStorage.getItem(HISTORY),[]);
  const state={stage:0,photos:{},issues:[],top3:[],actions:[],done:new Set(),reactions:{},pose:null,poseState:'idle',scanId:null,previous:null,bodyResult:null};
  const A='./assets/miss/';
  const ACTIONS={
    breathing:{type:'CARE',title:'90/90 Breathing',img:A+'90-90-breathing.svg',why:'胸郭と骨盤を重ねやすい位置を作り、rib flareの代償を減らす。',how:'かかとで壁を軽く押し、口から長く吐く。前の肋骨が下がった位置を保ったまま静かに吸う。',dose:'4〜5呼吸 × 2〜3set',feel:'ハム・腹部・脇腹',ng:'腰を反る／首に力を入れる'},
    thoracic:{type:'CARE',title:'胸椎伸展',img:A+'thoracic-extension.svg',why:'腰ではなく胸椎で伸展を出し、デコルテと肩ラインの土台を作る。',how:'胸の後ろにローラーを当て、呼気で肋骨を整えてから胸椎だけをゆっくり伸ばす。',dose:'6〜8回 × 2set',feel:'背中上部・胸まわり',ng:'腰だけ反る／首をつめる'},
    serratus:{type:'TRAINING / CONTROL',title:'Serratus Reach',img:A+'serratus-reach.svg',why:'肩甲骨を胸郭上で前へ滑らせ、肩・背中・デコルテの見え方を整える。',how:'肋骨を開かず、腕を天井へ伸ばす。肩をすくめず肩甲骨だけを前へスライドさせる。',dose:'8〜12回 × 2set',feel:'脇の下・前鋸筋・上背部',ng:'肩をすくめる／rib flare'},
    shoulderFlex:{type:'CARE',title:'Wall Shoulder Flexion',img:A+'wall-shoulder-flexion.svg',why:'肩屈曲ROMを、腰反りや肋骨の代償を減らした状態で出す。',how:'壁に背中を軽くつけて吐き、肋骨を整えたまま腕を上げる。',dose:'8〜10回 × 2set',feel:'脇・肩・上背部',ng:'腰を反る／肩をすくめる'},
    hipExt:{type:'CARE',title:'Half-Kneeling Hip Flexor',img:A+'hip-extension.svg',why:'股関節前面の余裕を作り、腰反りで脚を後ろへ出す代償を減らす。',how:'片膝立ちで骨盤を正面に保ち、お尻を軽く締めてから腰を反らず前へ体重移動。',dose:'30秒 × 2set / 左右',feel:'股関節前面・臀部',ng:'腰を反る／骨盤が横を向く'},
    hip90:{type:'CARE',title:'90/90 Hip Switch',img:A+'hip-90-90.svg',why:'股関節の内旋・外旋を左右で動かし、骨盤〜脚ラインの左右差を減らす。',how:'胸を正面に保ったまま、両膝を左右へゆっくり切り替える。',dose:'8〜10回 × 2set',feel:'臀部・股関節まわり',ng:'反動で倒す／痛みを我慢する'},
    adductor:{type:'CARE',title:'Adductor Rockback',img:A+'adductor-rockback.svg',why:'開脚に必要な内転筋と股関節の可動性を、腰の代償を減らして出す。',how:'四つ這いから片脚を横へ伸ばし、背中を長く保ったままお尻を後ろへ引く。',dose:'8〜10回 × 2set / 左右',feel:'内もも・股関節内側',ng:'腰を丸めすぎる／膝に痛み'},
    hamstring:{type:'CARE',title:'Hamstring Hinge',img:A+'hamstring-hinge.svg',why:'前屈を腰だけで作らず、股関節からたたむ動きを覚える。',how:'膝を少しゆるめ、お尻を後ろへ引きながら背中を長く保って前へ倒れる。',dose:'8〜10回 × 2set',feel:'ハムストリング・臀部',ng:'腰だけ丸める／反動を使う'},
    rdl:{type:'TRAINING',title:'RDL｜軽〜中負荷',img:A+'hamstring-hinge.svg',why:'股関節ヒンジが保てる範囲で臀部〜ハム後面を使い、大会でのヒップ〜脚後面ラインを作る。',how:'背中を長く保ち、股関節を後ろへ引く。ハムの伸張を感じる範囲で戻る。',dose:'8〜10回 × 2〜3set / RIR 2〜3',feel:'ハムストリング・臀部',ng:'腰が丸まる／反動／痛みを我慢する'}
  };
  const ISSUES={
    rib:{label:'胸郭―骨盤ポジション',impact:'ウエスト・デコルテの正面ラインに影響しやすい。',causes:['呼気で前側肋骨を下げにくい','腹斜筋・前鋸筋と呼吸の協調不足候補'],long:'6〜8週で胸郭と骨盤を重ねた姿勢を安定',week:'呼吸＋前鋸筋を優先',actions:['breathing','serratus']},
    breath:{label:'呼吸拡張の左右差',impact:'胸郭の左右差が肩・デコルテ・ウエストの見え方に影響する可能性。',causes:['片側優位の呼吸パターン候補','胸郭可動性の左右差候補'],long:'6〜8週で左右へ呼吸を広げやすくする',week:'90/90呼吸＋胸椎',actions:['breathing','thoracic']},
    thoracic:{label:'胸椎伸展・回旋',impact:'デコルテ、肩の開き、上肢挙上時のシルエットに影響。',causes:['胸椎伸展制限候補','腰椎伸展で代償している可能性'],long:'6〜8週で胸椎伸展を改善',week:'胸椎＋呼吸を優先',actions:['thoracic','shoulderFlex']},
    scap:{label:'肩甲骨コントロール左右差',impact:'肩・背中ラインと腕を上げた時の見え方に影響。',causes:['前鋸筋・下部僧帽筋の協調差候補','胸郭上での肩甲骨移動差候補'],long:'6〜8週で肩甲骨の左右差を縮小',week:'前鋸筋＋肩ROM',actions:['serratus','shoulderFlex']},
    shoulder:{label:'肩ラインの左右差',impact:'正面・背面の肩高差として見えやすい。',causes:['胸郭・肩甲骨位置の左右差候補','立位荷重差候補'],long:'6〜8週で肩ラインの左右差を縮小',week:'胸椎＋肩甲骨コントロール',actions:['thoracic','serratus']},
    shoulderRom:{label:'肩屈曲ROM左右差',impact:'腕・肩・背中・デコルテのラインに影響。',causes:['肩屈曲ROM制限候補','胸椎・肩甲骨との連動不足候補'],long:'6〜8週で肩屈曲の左右差を縮小',week:'肩ROM＋胸椎',actions:['shoulderFlex','thoracic']},
    pelvis:{label:'骨盤ラインの左右差',impact:'ウエスト〜ヒップ〜脚ラインの左右差として見えやすい。',causes:['片脚支持の左右差候補','股関節回旋・荷重差候補'],long:'6〜8週で骨盤〜脚ラインを安定',week:'股関節回旋＋伸展',actions:['hip90','hipExt']},
    hipExt:{label:'股関節伸展不足候補',impact:'ヒップ〜脚後面ラインと立位時の腰反りに影響。',causes:['股関節前面の可動性不足候補','腰椎伸展で代償している可能性'],long:'6〜8週で股関節伸展を改善',week:'股関節伸展＋ヒンジ',actions:['hipExt','rdl']},
    hipRot:{label:'股関節回旋左右差',impact:'膝・つま先・骨盤を含む脚ラインの左右差に影響。',causes:['内旋・外旋可動性の左右差候補','骨盤コントロール差候補'],long:'6〜8週で股関節回旋左右差を縮小',week:'90/90＋内もも',actions:['hip90','adductor']},
    hamstring:{label:'前屈・股関節ヒンジ',impact:'前屈、脚後面、骨盤の見え方と動作時の腰代償に影響。',causes:['ハムストリング可動性不足候補','股関節ヒンジ学習不足候補'],long:'6〜8週で股関節から前屈できる範囲を拡大',week:'ヒンジ＋ハム',actions:['hamstring','rdl']},
    adductor:{label:'開脚・内転筋可動性',impact:'開脚と内もも〜脚ラインの左右差に影響。',causes:['内転筋可動性差候補','股関節外転・回旋の左右差候補'],long:'6〜8週で開脚に必要な股関節可動性を改善',week:'内もも＋股関節回旋',actions:['adductor','hip90']},
    head:{label:'頭部位置',impact:'首〜デコルテ、正面・側面の上半身ラインに影響。',causes:['胸椎位置の影響候補','頸部で姿勢を補正している可能性'],long:'6〜8週で首〜胸郭の位置を安定',week:'胸椎＋呼吸',actions:['thoracic','breathing']},
    trunk:{label:'体幹位置',impact:'全身の立ち姿とシルエットの安定感に影響。',causes:['胸郭―骨盤位置の偏り候補','立位荷重差候補'],long:'6〜8週で体幹位置を安定',week:'呼吸＋胸椎',actions:['breathing','thoracic']},
    maintain:{label:'現在のライン維持',impact:'大きな差が出ていない部位は維持し、再評価で変化を追う。',causes:['現時点の簡易評価では大きな差を未検出'],long:'現在の良いラインを大会まで維持',week:'再現性＋回復管理',actions:['breathing','serratus']}
  };
  const mapLabel=label=>{const s=String(label||'');if(/肋骨|rib/i.test(s))return'rib';if(/胸椎/.test(s))return'thoracic';if(/肩甲/.test(s))return'scap';if(/肩/.test(s)&&/屈曲|ROM/.test(s))return'shoulderRom';if(/肩/.test(s))return'shoulder';if(/骨盤/.test(s))return'pelvis';if(/股関節.*伸展|伸展不足/.test(s))return'hipExt';if(/股関節.*回旋|内旋|外旋/.test(s))return'hipRot';if(/前屈|ハム/.test(s))return'hamstring';if(/開脚|内転/.test(s))return'adductor';if(/頭部|首/.test(s))return'head';return'trunk'};
  const sourceLabel=s=>s==='photo'?'写真':s==='check'?'セルフチェック':s==='body'?'BODY共通データ':'評価';
  const openDb=()=>new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});
  async function putPhoto(key,val){const d=await openDb();return new Promise((res,rej)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(val,key);t.oncomplete=()=>res();t.onerror=()=>rej(t.error)})}
  function addIssue(key,score,source,detail=''){const def=ISSUES[key]||ISSUES.trunk;state.issues.push({key,label:def.label,score:Number(score)||1,source,detail,impact:def.impact,causes:def.causes})}
  function dedupe(){const m=new Map;for(const i of state.issues){const p=m.get(i.key);if(!p||p.score<i.score)m.set(i.key,i)}state.issues=[...m.values()].sort((a,b)=>b.score-a.score)}
  function existingBodyIssues(){
    let result=null;
    try{result=window.SuGBeautyBody?.analyze?.()||safeJson(localStorage.getItem(BODY_KEY),null)?.result||null}catch{}
    state.bodyResult=result;
    if(!result?.areas)return;
    Object.entries(result.areas).forEach(([area,a])=>{
      (a?.issues||[]).forEach((label,idx)=>addIssue(mapLabel(label),Math.max(2.4,4.1-idx*.25),'body',`${area}｜${label}`));
    });
    if(Number.isFinite(result.movementQuality)&&result.movementQuality<70)addIssue('trunk',3.2,'body',`Movement Quality ${result.movementQuality}`);
  }
  function bindExistingManual(){try{const s=window.SuGBeautyBody?.getState?.();return {pain:Number(s?.manual?.pain)||0,fatigue:Number(s?.manual?.fatigue)||0}}catch{return {pain:0,fatigue:0}}}
  function shellHtml(){return `<div class="missi-shell" id="missiShell" hidden><header class="missi-top"><div class="missi-toprow"><button class="missi-close" id="missiClose">×</button><div class="missi-title"><b>MISS OF · BODY LOOP</b><span id="missiStageLabel">SELF SCAN</span></div></div><div class="missi-progress"><i id="missiProgress"></i></div></header><main class="missi-main" id="missiContent"></main></div><div class="missi-sheet" id="missiSheet" hidden><div class="missi-sheetin" id="missiSheetIn"></div></div>`}
  function inject(){
    const hero=$('hero')||document.querySelector('.hero');if(!hero)return false;
    const entry=document.createElement('section');entry.id='missOfIntegratedEntry';entry.className='card missi-entry';entry.innerHTML=`<div class="eyebrow">MISS OF · SELF ASSESSMENT</div><h2>撮影から、今日やることまで。</h2><div class="sub">元のS.u.G BODYの「測定 → 判断 → 行動 → 身体反応 → 再判断」に、大会でどう見えるかの解釈を重ねます。</div><div class="missi-flowline"><span>撮影・評価</span><span>左右差/課題</span><span>原因候補</span><span>TOP3</span><span>長期</span><span>今週</span><span>今日</span></div><button class="btn" id="missiStart">大会BODY｜セルフ評価を始める</button>`;
    hero.appendChild(entry);document.body.insertAdjacentHTML('beforeend',shellHtml());
    $('missiStart').onclick=openShell;$('missiClose').onclick=closeShell;$('missiSheet').onclick=e=>{if(e.target.id==='missiSheet')closeSheet()};
    return true;
  }
  function setStage(n,label){state.stage=n;$('missiProgress').style.width=`${[25,50,75,100][n]||25}%`;$('missiStageLabel').textContent=label}
  function openShell(){document.body.style.overflow='hidden';$('missiShell').hidden=false;renderScan()}
  function closeShell(){document.body.style.overflow='';$('missiShell').hidden=true;closeSheet()}
  function closeSheet(){$('missiSheet').hidden=true;$('missiSheetIn').innerHTML=''}
  function previousAssessment(){const h=history();return h.length?h[h.length-1]:null}
  function bodyDataSummary(){let r=state.bodyResult;try{r=r||window.SuGBeautyBody?.analyze?.()}catch{}const rec=Number(r?.recovery);const mq=Number(r?.movementQuality);return `<div class="missi-source"><span class="missi-pill body">BODY共通データ ${r?'接続':'未取得'}</span>${Number.isFinite(rec)?`<span class="missi-pill">Recovery ${Math.round(rec)}</span>`:''}${Number.isFinite(mq)?`<span class="missi-pill">Movement ${Math.round(mq)}</span>`:''}</div>`}
  function renderScan(){
    setStage(0,'SELF SCAN');state.previous=previousAssessment();
    $('missiContent').innerHTML=`<section class="missi-hero"><div class="missi-eye">01 · MEASURE</div><h2>撮る。測る。<br>まず違いを見る。</h2><p>正面・側面・背面写真とセルフチェック、既存BODYデータを統合します。写真だけで傷病名や原因を断定しません。</p>${bodyDataSummary()}</section><section class="missi-card"><h3>正面・側面・背面</h3><div class="missi-sub">同じ距離・高さ・自然立位で撮影。写真は元BODYと同じIndexedDBに保存します。</div><div class="missi-captures">${['front','side','back'].map(v=>`<label class="missi-cap"><input data-view="${v}" type="file" accept="image/*" capture="environment"><img id="missiImg_${v}"><b>${v==='front'?'正面':v==='side'?'側面':'背面'}</b><span>タップして撮影</span></label>`).join('')}</div></section><section class="missi-card"><h3>追加セルフチェック</h3><div class="missi-checks">${[
      ['rib','息を吐いても前の下側の肋骨が浮きやすい','胸郭―骨盤ポジション'],['breath','吸った時の胸郭の広がりに左右差を感じる','呼吸拡張左右差'],['thoracic','両腕を上げると腰を反って代償しやすい','胸椎・肩甲帯'],['scap','腕を上げた時、左右で肩甲骨の動きが違う','肩甲骨コントロール'],['shoulderRom','腕を真上まで上げにくい／左右差がある','肩屈曲ROM'],['hipExt','片脚を後ろへ引くと腰を反らないと伸びない','股関節伸展'],['hipRot','90/90座位で左右どちらかが明らかにやりにくい','股関節回旋'],['hamstring','前屈で股関節から倒れにくい','前屈・ヒンジ'],['adductor','開脚で内ももが強く詰まる／左右差がある','開脚・内転筋']
    ].map(x=>`<label class="missi-check"><input type="checkbox" data-issue="${x[0]}"><div><b>${x[1]}</b><span>${x[2]}</span></div></label>`).join('')}</div><div class="missi-safety">痛み・しびれ・強い症状がある場合は負荷を中止し、必要な医療評価を優先してください。</div><button class="missi-btn" id="missiAnalyze">写真＋BODY＋セルフチェックを統合</button></section>`;
    $('missiContent').querySelectorAll('input[type=file]').forEach(inp=>inp.onchange=e=>onPhoto(e.target));$('missiAnalyze').onclick=analyze;
  }
  async function onPhoto(input){const file=input.files?.[0];if(!file)return;const view=input.dataset.view;state.photos[view]=file;const img=$(`missiImg_${view}`);img.src=URL.createObjectURL(file);img.style.visibility='visible';try{await putPhoto(`miss:${nowDate()}:${view}`,file)}catch(e){console.warn('MISS photo store',e)}}
  async function ensurePose(){if(state.pose)return state.pose;if(state.poseState==='failed')return null;state.poseState='loading';try{const mod=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/+esm');const files=await mod.FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/wasm');state.pose=await mod.PoseLandmarker.createFromOptions(files,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task'},runningMode:'IMAGE',numPoses:1});state.poseState='ready';return state.pose}catch(e){state.poseState='failed';console.warn('MISS pose unavailable',e);return null}}
  const imageFromBlob=blob=>new Promise((res,rej)=>{const im=new Image(),u=URL.createObjectURL(blob);im.onload=()=>{URL.revokeObjectURL(u);res(im)};im.onerror=e=>{URL.revokeObjectURL(u);rej(e)};im.src=u});
  const deg=(a,b)=>Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI,dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),mid=(a,b)=>({x:(a.x+b.x)/2,y:(a.y+b.y)/2});
  function photoIssues(view,lm){const L=i=>lm?.[i];if(view!=='side'){const a=L(11),b=L(12),c=L(23),d=L(24);if(a&&b){let x=Math.abs(deg(a,b));x=Math.min(x,Math.abs(180-x));if(x>2.2)addIssue('shoulder',Math.min(5,2+x/2),'photo',`肩ライン ${x.toFixed(1)}°`)}if(c&&d){let x=Math.abs(deg(c,d));x=Math.min(x,Math.abs(180-x));if(x>2.2)addIssue('pelvis',Math.min(5,2+x/2),'photo',`骨盤ライン ${x.toFixed(1)}°`)}const e=L(7),f=L(8);if(e&&f&&a&&b){const o=Math.abs(mid(e,f).x-mid(a,b).x)/(dist(a,b)||.1);if(o>.10)addIssue('head',Math.min(4.5,2+o*8),'photo',`頭部偏位 ${Math.round(o*100)}% shoulder幅`)}}else{const e=L(7)||L(8),a=L(11)||L(12),h=L(23)||L(24);if(e&&a&&h){const t=dist(a,h)||.1,f=Math.abs(e.x-a.x)/t,lean=Math.abs(a.x-h.x)/t;if(f>.13)addIssue('head',Math.min(5,2+f*7),'photo',`頭部前方 ${Math.round(f*100)}% torso`);if(lean>.10)addIssue('trunk',Math.min(4.5,2+lean*7),'photo',`体幹位置 ${Math.round(lean*100)}% torso`)}}}
  function checkIssues(){document.querySelectorAll('#missiContent [data-issue]:checked').forEach((el,idx)=>addIssue(el.dataset.issue,4.8-Math.min(idx*.04,.5),'check','本人セルフチェック'))}
  async function analyze(){
    state.issues=[];existingBodyIssues();checkIssues();const button=$('missiAnalyze');button.disabled=true;button.textContent='統合中…';
    try{const pose=Object.keys(state.photos).length?await ensurePose():null;if(pose){for(const [view,file] of Object.entries(state.photos)){try{const im=await imageFromBlob(file),lm=pose.detect(im)?.landmarks?.[0];if(lm)photoIssues(view,lm)}catch(e){console.warn('MISS photo analysis',view,e)}}}dedupe();if(!state.issues.length)addIssue('maintain',1,'body','大きな差は簡易評価で未検出');dedupe();state.scanId=`${Date.now()}`;saveAssessment();renderDifference()}finally{button.disabled=false;button.textContent='写真＋BODY＋セルフチェックを統合'}
  }
  function compareText(issue){const prev=state.previous?.issues?.find(x=>x.key===issue.key);if(!prev)return'初回比較';const d=issue.score-Number(prev.score||0);if(d<=-.5)return'前回より差が小さい';if(d>=.5)return'前回より差が大きい';return'前回と同程度'}
  function renderDifference(){setStage(1,'WHAT → WHY');$('missiContent').innerHTML=`<section class="missi-hero"><div class="missi-eye">02 · WHAT IS DIFFERENT?</div><h2>何が違う？<br>原因候補は何？</h2><p>「歪み」と断定せず、写真・セルフチェック・BODY共通データを分けて表示します。</p></section><section class="missi-card">${state.issues.map(i=>`<div class="missi-issue"><div class="missi-issuehead"><b>${i.label}</b><span class="missi-badge">${sourceLabel(i.source)}</span></div><div class="missi-impact">WHAT｜${i.impact}</div><div class="missi-cause">WHY候補｜${i.causes.join('／')}</div>${i.detail?`<div class="missi-delta">${i.detail}｜${compareText(i)}</div>`:''}</div>`).join('')}<button class="missi-btn" id="missiMakePlan">課題TOP3 → 長期 → 今週 → 今日へ</button><button class="missi-btn secondary" id="missiBackScan">撮影・評価へ戻る</button></section>`;$('missiMakePlan').onclick=makePlan;$('missiBackScan').onclick=renderScan}
  function pastReactionScore(k){let score=0;for(const h of history().slice(-8)){const r=h?.reactions?.[k];if(r==='better')score+=2;else if(r==='worse')score-=3}return score}
  function gateTraining(){const manual=bindExistingManual();if(manual.pain>=4)return false;try{const keys=state.top3.map(x=>x.key);const area=keys.some(k=>['hipExt','hipRot','hamstring','adductor','pelvis'].includes(k))?'legs':keys.some(k=>['shoulder','shoulderRom','scap','thoracic'].includes(k))?'decollete':'waist';return window.SuGBeautyBody?.overloadGate?.(area)?.allow!==false}catch{return true}}
  function chooseActions(){const keys=[];for(const i of state.top3){for(const k of (ISSUES[i.key]||ISSUES.trunk).actions)if(!keys.includes(k))keys.push(k)}if(!gateTraining()){const ix=keys.indexOf('rdl');if(ix>=0)keys.splice(ix,1)}keys.sort((a,b)=>pastReactionScore(b)-pastReactionScore(a));while(keys.length<3){for(const k of ['breathing','thoracic','serratus'])if(!keys.includes(k)){keys.push(k);break}else break}return keys.slice(0,3)}
  function makePlan(){state.top3=state.issues.filter(i=>i.key!=='maintain').slice(0,3);if(!state.top3.length)state.top3=[state.issues[0]];state.actions=chooseActions();const today=safeJson(localStorage.getItem(TODAY),null);if(today?.date===nowDate()){state.done=new Set(today.done||[]);state.reactions=today.reactions||{}}saveAssessment();renderPlan()}
  function renderPlan(){setStage(2,'TOP3 → LONG TERM → WEEK → TODAY');const long=[...new Set(state.top3.map(i=>(ISSUES[i.key]||ISSUES.trunk).long))].join('・');const week=[...new Set(state.top3.map(i=>(ISSUES[i.key]||ISSUES.trunk).week))].join('＋');$('missiContent').innerHTML=`<section class="missi-hero"><div class="missi-eye">03 · PRIORITY</div><h2>課題TOP3から、<br>今日まで落とす。</h2><p>大会でどう見えるかを基準に優先順位をつけ、元BODYの回復・痛み・動作品質ゲートを越えた範囲だけ実施します。</p></section><section class="missi-card"><div class="missi-top3">${state.top3.map((p,i)=>`<div class="missi-pri"><div class="missi-prihead"><div class="missi-rank">${i+1}</div><h4>${p.label}</h4></div><p>WHAT｜${p.impact}</p><p>WHY候補｜${p.causes.join('／')}</p></div>`).join('')}</div></section><section class="missi-card"><div class="missi-planrow"><small>LONG TERM · 6–8 WEEKS</small><b>${long}</b></div><div class="missi-planrow"><small>THIS WEEK</small><b>${week}</b></div><div class="missi-planrow"><small>TODAY</small><b>TOP3と過去の身体反応から、今日やる3つだけ表示。</b></div></section><section class="missi-card"><h3>今日やること</h3><div class="missi-actions">${state.actions.map(actionCard).join('')}</div><div class="missi-safety">実施後は「良くなった／同じ／悪くなった」を残します。次回はその身体反応も使って再判断します。</div><button class="missi-btn secondary" id="missiBackResult">結果へ戻る</button></section>`;$('missiContent').querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>openAction(b.dataset.action));$('missiBackResult').onclick=renderDifference}
  function actionCard(k){const a=ACTIONS[k],r=state.reactions[k];return `<button class="missi-action ${state.done.has(k)?'done':''}" data-action="${k}"><img src="${a.img}" alt="${a.title}"><div><small>${a.type}</small><b>${a.title}</b><span>${a.dose}</span>${r?`<span>身体反応：${r==='better'?'良くなった':r==='same'?'同じ':'悪くなった'}</span>`:''}</div></button>`}
  function openAction(k){const a=ACTIONS[k];if(!a)return;$('missiSheetIn').innerHTML=`<img src="${a.img}" alt="${a.title}"><small class="missi-eye">${a.type}</small><h3>${a.title}</h3><div class="missi-sub">WHY｜${a.why}</div><div class="missi-info"><div><small>やり方</small><b>${a.how}</b></div><div><small>回数</small><b>${a.dose}</b></div><div><small>感じる場所</small><b>${a.feel}</b></div><div><small>NG</small><b>${a.ng}</b></div></div><button class="missi-btn" id="missiDoneAction">${state.done.has(k)?'完了済み':'この種目を完了'}</button><div class="missi-reactions"><button class="missi-react ${state.reactions[k]==='better'?'on':''}" data-r="better">良くなった</button><button class="missi-react ${state.reactions[k]==='same'?'on':''}" data-r="same">同じ</button><button class="missi-react ${state.reactions[k]==='worse'?'on':''}" data-r="worse">悪くなった</button></div><button class="missi-btn secondary" id="missiCloseAction">閉じる</button>`;$('missiSheet').hidden=false;$('missiDoneAction').onclick=()=>{state.done.add(k);persistToday();saveAssessment();$('missiDoneAction').textContent='完了済み'};$('missiSheetIn').querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{state.reactions[k]=b.dataset.r;state.done.add(k);persistToday();saveAssessment();openAction(k)});$('missiCloseAction').onclick=()=>{closeSheet();renderActionProgress()}}
  function renderActionProgress(){setStage(3,'BODY RESPONSE → REASSESS');$('missiContent').innerHTML=`<section class="missi-hero"><div class="missi-eye">04 · RESPONSE</div><h2>やった後を残す。<br>次の判断につなぐ。</h2><p>実施だけで終わらず、身体反応と再評価を次の優先順位へつなぎます。</p></section><section class="missi-card"><h3>今日の完了</h3><div class="missi-actions">${state.actions.map(actionCard).join('')}</div><div class="missi-planrow"><small>BODY RESPONSE</small><b>${state.actions.map(k=>`${ACTIONS[k].title}：${state.reactions[k]==='better'?'良くなった':state.reactions[k]==='same'?'同じ':state.reactions[k]==='worse'?'悪くなった':'未入力'}`).join(' / ')}</b></div><button class="missi-btn" id="missiReassess">再評価を始める</button><button class="missi-btn secondary" id="missiCloseFinish">MISS OFへ戻る</button></section>`;$('missiContent').querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>openAction(b.dataset.action));$('missiReassess').onclick=()=>{state.photos={};state.issues=[];state.top3=[];state.actions=[];state.done=new Set();state.reactions={};renderScan()};$('missiCloseFinish').onclick=closeShell}
  function persistToday(){localStorage.setItem(TODAY,JSON.stringify({date:nowDate(),done:[...state.done],reactions:state.reactions,top3:state.top3.map(x=>x.key),actions:state.actions}))}
  function saveAssessment(){const h=history();const rec={id:state.scanId||`${Date.now()}`,at:new Date().toISOString(),version:VERSION,issues:state.issues.map(x=>({...x})),top3:state.top3.map(x=>({...x})),actions:[...state.actions],done:[...state.done],reactions:{...state.reactions},body:{movementQuality:state.bodyResult?.movementQuality??null,recovery:state.bodyResult?.recovery??null}};const ix=h.findIndex(x=>x.id===rec.id);if(ix>=0)h[ix]=rec;else h.push(rec);localStorage.setItem(HISTORY,JSON.stringify(h.slice(-24)));window.dispatchEvent(new CustomEvent('sug:miss-assessment',{detail:rec}));window.dispatchEvent(new CustomEvent('sug:body-response',{detail:{assessmentId:rec.id,reactions:rec.reactions,done:rec.done}}))}
  function boot(){if(!inject())setTimeout(boot,150)}
  boot();
  window.SuGMissOfIntegrated={version:VERSION,open:openShell,history,actions:ACTIONS,issues:ISSUES};
})();
