const A='./assets/miss/',S={img:{},metrics:{},issues:[],pri:[],done:new Set(),cur:null};
const E={breathing:{t:'90/90 Breathing',i:A+'90-90-breathing.svg',w:'完全呼気で前側の肋骨を下げ、胸郭と骨盤を重ねる位置づくり。',d:'4〜5呼吸 × 2〜3set',f:'ハム・お腹・脇腹',c:'吐く時にみぞおちが少しへこみ、腰が反らない',n:'腰を反る／首に力'},wall:{t:'Wall Press Breathing',i:A+'wall-press-breathing.svg',w:'壁を押して前鋸筋・腹斜筋を使い、rib flareを出さず呼吸。',d:'4〜5呼吸 × 2set',f:'腹斜筋・前鋸筋・脇腹',c:'吸う時も前の肋骨が開かない',n:'胸を張りすぎる／腰を反る／肩をすくめる'},thoracic:{t:'胸椎伸展',i:A+'thoracic-extension.svg',w:'腰の代償ではなく胸椎の伸展を出し、デコルテ・肩ラインの土台を作る。',d:'6〜8回 × 2set',f:'背中上部・胸まわり',c:'腰ではなく胸の後ろが動く',n:'腰だけ反る／首をつめる'},serratus:{t:'Serratus Reach',i:A+'serratus-reach.svg',w:'前鋸筋で肩甲骨を胸郭上で前へ滑らせ、肩・デコルテラインを整える。',d:'8〜12回 × 2set',f:'脇の下・前鋸筋・上背部',c:'肩をすくめず肋骨が前に開かない',n:'肩をすくめる／rib flare'}};
const IMP={rib:'ウエスト・デコルテ：胸郭と骨盤が重なりにくくラインが崩れやすい',thoracic:'デコルテ・肩：腕挙上で腰の代償が出やすい',scap:'肩・背中：肩甲骨コントロール差が肩ラインに影響',shoulder:'肩・デコルテ：肩高差が正面シルエットに出やすい',pelvis:'ウエスト・脚：骨盤差がウエスト〜脚ラインに影響',head:'首・デコルテ：頭部位置が首〜上半身の見え方に影響',trunk:'全身：体幹位置が立ち姿の安定感に影響'};
const $=id=>document.getElementById(id),mid=(a,b)=>({x:(a.x+b.x)/2,y:(a.y+b.y)/2}),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),deg=(a,b)=>Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI;
function bind(fid,iid,cid,k){$(fid).onchange=()=>{const f=$(fid).files?.[0];if(!f)return;const u=URL.createObjectURL(f),im=$(iid);im.onload=()=>{$(cid).classList.add('has');S.img[k]=im};im.src=u}}bind('frontFile','frontImg','capFront','front');bind('sideFile','sideImg','capSide','side');bind('backFile','backImg','capBack','back');
function add(k,l,sc,src,m=''){S.issues.push({k,l,sc,src,m,impact:IMP[k]||''})}
function photo(view,lm){const L=i=>lm[i];if(view!=='side'){const a=L(11),b=L(12),c=L(23),d=L(24);if(a&&b){let x=Math.abs(deg(a,b));x=Math.min(x,Math.abs(180-x));S.metrics[view+'ShoulderTilt']=x;if(x>2.2)add('shoulder','肩ラインの左右差',2+x/2,'photo',x.toFixed(1)+'°')}if(c&&d){let x=Math.abs(deg(c,d));x=Math.min(x,Math.abs(180-x));S.metrics[view+'PelvisTilt']=x;if(x>2.2)add('pelvis','骨盤ラインの左右差',2+x/2,'photo',x.toFixed(1)+'°')}const e=L(7),f=L(8);if(e&&f&&a&&b){const o=Math.abs(mid(e,f).x-mid(a,b).x)/(dist(a,b)||.1);S.metrics[view+'HeadOffset']=o;if(o>.1)add('head','頭部の左右偏位',2+o*8,'photo',Math.round(o*100)+'% shoulder幅')}}else{const e=L(7)||L(8),a=L(11)||L(12),h=L(23)||L(24);if(e&&a&&h){const t=dist(a,h)||.1,f=Math.abs(e.x-a.x)/t,lean=Math.abs(a.x-h.x)/t;S.metrics.forwardHead=f;S.metrics.trunkLean=lean;if(f>.13)add('head','頭部前方位の傾向',2+f*7,'photo',Math.round(f*100)+'% torso');if(lean>.1)add('trunk','体幹前後位置の偏り',2+lean*7,'photo',Math.round(lean*100)+'% torso')}}}
function checks(){if($('ribCheck').checked)add('rib','rib flare 傾向',5,'check','呼気でも前側肋骨が浮く');if($('thoracicCheck').checked)add('thoracic','胸椎伸展の追加評価候補',4.5,'check','腕挙上で腰椎伸展代償');if($('scapCheck').checked)add('scap','肩甲骨コントロール左右差',4,'check','左右差の自覚');if(!S.issues.length)add('trunk','大きな左右差は簡易評価で未検出',1,'good')}
function dedupe(){const m=new Map;for(const i of S.issues)if(!m.has(i.k)||m.get(i.k).sc<i.sc)m.set(i.k,i);S.issues=[...m.values()].sort((a,b)=>b.sc-a.sc)}
async function analyze(){S.issues=[];S.metrics={};$('loading').classList.add('on');try{for(const v of ['front','side','back'])if(S.img[v]&&window.pose){const lm=await window.pose(S.img[v]);if(lm)photo(v,lm)}checks();dedupe();renderIssues();saveScan();$('resultCard').classList.remove('hidden');$('resultCard').scrollIntoView({behavior:'smooth'})}finally{$('loading').classList.remove('on')}}
function renderIssues(){$('issues').innerHTML=S.issues.map(i=>`<div class="issue"><div class="itop"><b>${i.l}</b><span class="pill ${i.src==='photo'?'photo':i.src==='check'?'check':''}">${i.src==='photo'?'写真で検出':i.src==='check'?'追加チェック':'良好'}</span></div><div class="impact">${i.impact||'現時点の簡易評価では大きな位置差を確認していません。'}</div><div class="metric">${i.m}</div></div>`).join('');history()}
function saveScan(){try{const h=JSON.parse(localStorage.getItem('sug_miss_selfcoach_history')||'[]');h.push({at:new Date().toISOString(),metrics:S.metrics,issues:S.issues});localStorage.setItem('sug_miss_selfcoach_history',JSON.stringify(h.slice(-12)))}catch{}}
function history(){try{const h=JSON.parse(localStorage.getItem('sug_miss_selfcoach_history')||'[]'),p=h.length>1?h[h.length-2]:null;if(!p)return;const r=[];for(const k in S.metrics)if(Number.isFinite(p.metrics?.[k])){const d=S.metrics[k]-p.metrics[k];r.push(`${k}: ${d>0?'+':''}${d.toFixed(2)}`)}$('history').textContent=r.length?'前回差：'+r.slice(0,4).join(' / '):'前回データあり。同じ測定項目が不足。'}catch{}}
function plan(){S.pri=S.issues.filter(i=>i.src!=='good').slice(0,3);if(!S.pri.length)S.pri=[{k:'trunk',l:'姿勢維持',impact:'現状維持'}];$('top3').innerHTML=S.pri.map((p,i)=>`<div class="pri"><div class="rank">${i+1}</div><div><b>${p.l}</b><span>${p.impact||IMP[p.k]||''}</span></div></div>`).join('');const K=S.pri.map(x=>x.k),L=[];if(K.includes('rib'))L.push('胸郭と骨盤のstackを安定');if(K.includes('thoracic'))L.push('胸椎伸展を改善');if(K.some(k=>['scap','shoulder'].includes(k)))L.push('肩甲骨・肩ラインの左右差を縮小');if(K.includes('pelvis'))L.push('骨盤〜脚ラインの左右差を縮小');if(K.includes('head'))L.push('頭部位置を整え首〜デコルテを安定');if(!L.length)L.push('現在のラインを維持し動作中も崩れにくくする');$('longTerm').textContent='6〜8週間で '+L.join('・')+'。';const W=[];if(K.includes('rib'))W.push('呼吸');if(K.includes('thoracic'))W.push('胸椎');if(K.some(k=>['scap','shoulder'].includes(k)))W.push('前鋸筋・肩甲骨');if(K.includes('pelvis'))W.push('骨盤コントロール');$('week').textContent=(W.length?W.join('＋'):'呼吸＋胸椎＋肩甲骨')+'を優先。';renderEx();$('planCard').classList.remove('hidden');$('finish').classList.remove('hidden');$('planCard').scrollIntoView({behavior:'smooth'})}
function renderEx(){const o=['breathing','wall','thoracic','serratus'];$('exgrid').innerHTML=o.map(k=>`<button class="ex ${S.done.has(k)?'done':''}" data-k="${k}"><img src="${E[k].i}"><div><b>${E[k].t}</b><span>${E[k].d}</span></div></button>`).join('');document.querySelectorAll('.ex').forEach(x=>x.onclick=()=>openEx(x.dataset.k))}
function openEx(k){const e=E[k];S.cur=k;$('mimg').src=e.i;$('mtitle').textContent=e.t;$('mwhy').textContent=e.w;$('mdose').textContent=e.d;$('mfeel').textContent=e.f;$('mcheck').textContent=e.c;$('mng').textContent=e.n;$('modal').classList.add('on')}
function close(){ $('modal').classList.remove('on') }$('completeBtn').onclick=()=>{if(S.cur)S.done.add(S.cur);renderEx();close()};$('closeBtn').onclick=close;$('modal').onclick=e=>{if(e.target.id==='modal')close()};$('analyzeBtn').onclick=analyze;$('planBtn').onclick=plan;$('saveBtn').onclick=()=>{try{localStorage.setItem('sug_miss_today_'+new Date().toISOString().slice(0,10),JSON.stringify([...S.done]))}catch{}alert(`今日の実施 ${S.done.size}/4 種目を保存しました`)};
try{const {FilesetResolver,PoseLandmarker}=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/+esm'),V=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/wasm'),P=await PoseLandmarker.createFromOptions(V,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task'},runningMode:'IMAGE',numPoses:1});window.pose=async im=>P.detect(im)?.landmarks?.[0]||null;$('aiStatus').textContent='姿勢AI READY';$('aiStatus').classList.add('ok')}catch(e){console.warn(e);$('aiStatus').textContent='AI未接続・チェックのみ'}
