(()=>{
'use strict';
const VERSION='27.80';
const NUT_KEY='sug_nutrition_v2778';
const MEALS_KEY='sug_food_ai_meals_v2779';
const HEALTH_KEY='sug_native_health_v1';
const n=v=>Number.isFinite(Number(v))?Number(v):null;
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}};
const day=()=>{const d=new Date(),p=x=>String(x).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
function aggregateMeals(){const xs=read(MEALS_KEY,[]).filter(x=>x?.date===day());if(!xs.length)return null;const sum=k=>xs.reduce((s,x)=>s+(n(x?.[k])||0),0);return{date:day(),kcal:sum('kcal'),proteinG:sum('proteinG'),fatG:sum('fatG'),carbsG:sum('carbsG'),fiberG:sum('fiberG'),waterMl:sum('waterMl'),sodiumMg:sum('sodiumMg'),potassiumMg:sum('potassiumMg'),calciumMg:sum('calciumMg'),magnesiumMg:sum('magnesiumMg'),ironMg:sum('ironMg'),zincMg:sum('zincMg'),vitaminDUg:sum('vitaminDUg'),mealCount:xs.length};}
function state(){const saved=read(NUT_KEY,{}),daily=aggregateMeals()||saved.daily||null,targets=saved.targets||null,health=window.__SUG_NATIVE_HEALTH__||read(HEALTH_KEY,{});return{daily,targets,health};}
function gap(v,t){v=n(v);t=n(t);if(v==null||t==null||t<=0)return null;return Math.max(0,t-v)}
function pct(v,t){v=n(v);t=n(t);return v!=null&&t>0?v/t:null}
function analyze(){const s=state(),d=s.daily||{},t=s.targets||{},h=s.health||{};const g={kcal:gap(d.kcal??d.energyKcal,t.kcal??t.energyKcal??t.targetKcal),proteinG:gap(d.proteinG??d.protein,t.proteinG??t.protein??t.targetProteinG),fatG:gap(d.fatG??d.fat,t.fatG??t.fat??t.targetFatG),carbsG:gap(d.carbsG??d.carbs,t.carbsG??t.carbs??t.targetCarbsG),fiberG:gap(d.fiberG??d.fiber,t.fiberG??t.fiber??t.targetFiberG),waterMl:gap(d.waterMl??d.fluidMl,t.waterMl??t.fluidMl??t.targetWaterMl),ironMg:gap(d.ironMg,t.ironMg??t.targetIronMg),calciumMg:gap(d.calciumMg,t.calciumMg??t.targetCalciumMg),magnesiumMg:gap(d.magnesiumMg,t.magnesiumMg??t.targetMagnesiumMg),zincMg:gap(d.zincMg,t.zincMg??t.targetZincMg),potassiumMg:gap(d.potassiumMg,t.potassiumMg??t.targetPotassiumMg),vitaminDUg:gap(d.vitaminDUg??d.vitaminDug,t.vitaminDUg??t.vitaminDug??t.targetVitaminDUg)};
const ratios={kcal:pct(d.kcal??d.energyKcal,t.kcal??t.energyKcal??t.targetKcal),protein:pct(d.proteinG??d.protein,t.proteinG??t.protein??t.targetProteinG),carbs:pct(d.carbsG??d.carbs,t.carbsG??t.carbs??t.targetCarbsG),water:pct(d.waterMl??d.fluidMl,t.waterMl??t.fluidMl??t.targetWaterMl)};
const recovery=n(h.recoveryScore),stress=n(h.stressScore),exercise=n(h.exerciseMinutes),mode=String(document.getElementById('mode')?.textContent||'');
const priority=[];
if(ratios.kcal!=null&&ratios.kcal<.75)priority.push({key:'energy',label:'エネルギー',reason:'摂取量が目標より少ない'});
if(ratios.carbs!=null&&ratios.carbs<.75&&((exercise||0)>=30||(recovery!=null&&recovery<70)||/OVERLOAD|SHAPE/.test(mode)))priority.push({key:'carbs',label:'炭水化物',reason:'運動・回復に対して不足候補'});
if(ratios.protein!=null&&ratios.protein<.8)priority.push({key:'protein',label:'たんぱく質',reason:'修復材料を確保'});
if(ratios.water!=null&&ratios.water<.8)priority.push({key:'water',label:'水分',reason:'むくみだけを理由に水分を削らない'});
for(const [key,label] of [['ironMg','鉄'],['calciumMg','カルシウム'],['magnesiumMg','マグネシウム'],['potassiumMg','カリウム'],['vitaminDUg','ビタミンD']]){if(g[key]!=null){const target=n(t[key]??t['target'+key[0].toUpperCase()+key.slice(1)]);const val=n(d[key]);if(target>0&&val/target<.8)priority.push({key,label,reason:'今日の摂取目標に対して不足候補'})}}
const actions=[];
if(priority.some(x=>x.key==='carbs'))actions.push('主食を抜かず、ごはん・いも類・果物などから炭水化物を補う');
if(priority.some(x=>x.key==='protein'))actions.push('魚・肉・卵・大豆・乳製品など、たんぱく源を1品足す');
if(priority.some(x=>x.key==='ironMg'))actions.push('鉄を含む食品を意識。血液検査で異常がある場合は食事だけで自己判断しない');
if(priority.some(x=>x.key==='calciumMg'))actions.push('乳製品・小魚・大豆などからカルシウム候補を追加');
if(priority.some(x=>x.key==='magnesiumMg'))actions.push('豆類・海藻・ナッツ・全粒穀物などを候補にする');
if(priority.some(x=>x.key==='potassiumMg'))actions.push('野菜・果物・いも類などを候補にする');
if(priority.some(x=>x.key==='vitaminDUg'))actions.push('魚・卵などを候補にし、検査値がある場合は医療確認も優先');
if(priority.some(x=>x.key==='water'))actions.push('水分をこまめに補給する');
if((recovery!=null&&recovery<60)||(stress!=null&&stress>=70)){actions.unshift('今日は「さらに削る」より、回復条件を崩さない食事を優先');}
if(!actions.length&&s.targets)actions.push('大きな不足候補なし。残りは普段のバランスを維持');
const confidence=s.daily&&s.targets?'HIGH':s.daily||s.targets?'MEDIUM':'LOW';
return{version:VERSION,daily:s.daily,targets:s.targets,gaps:g,priority:priority.slice(0,6),actions:actions.slice(0,6),recovery,stress,exercise,mode,confidence,generatedAt:new Date().toISOString()};}
function fmt(v,unit,round=0){return v==null?'--':`${round?Number(v).toFixed(round):Math.round(v)}${unit}`}
function style(){if(document.getElementById('sugNextMealStyle2780'))return;const s=document.createElement('style');s.id='sugNextMealStyle2780';s.textContent=`.sugNextMeal{margin-top:12px;border-top:1px solid #272a2f;padding-top:12px}.sugNextTitle{color:#f0cc77;font-size:9px;font-weight:1000;letter-spacing:.08em}.sugGapRow{display:flex;gap:6px;overflow:auto;margin-top:8px}.sugGap{flex:0 0 auto;border:1px solid #4d3541;border-radius:999px;padding:7px 9px;background:#151015;color:#ffd0e2;font-size:8px}.sugGap.blue{border-color:#2e4b5e;background:#0b151c;color:#c9e2ef}.sugNextAction{padding:8px 0;border-top:1px solid #24292d;color:#c7c9ce;font-size:9px;line-height:1.5}.sugTargetForm{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:9px}.sugTargetForm label{font-size:7px;color:#767983}.sugTargetForm input{width:100%;margin-top:4px;border:1px solid #303139;border-radius:9px;background:#0d0d10;color:#fff;padding:9px;font-size:11px}.sugTargetBtn{width:100%;margin-top:8px;border:1px solid #5f4a24;border-radius:10px;background:#15120d;color:#f0cc77;padding:10px;font-size:9px;font-weight:900}`;document.head.appendChild(s)}
function host(){return document.querySelector('#sugNutrition2778 .sugNutIn')||document.getElementById('sugNutrition2778')}
function mount(){style();const h=host();if(!h||document.getElementById('sugNextMeal2780'))return;const box=document.createElement('div');box.id='sugNextMeal2780';box.className='sugNextMeal';box.innerHTML=`<div class="sugNextTitle">NEXT MEAL · 今日あと何を足す？</div><div id="sugNextGap2780" class="sugGapRow"></div><div id="sugNextActions2780"></div><details class="details" style="margin-top:8px"><summary>1日の目標を設定</summary><div class="inside"><div class="sugTargetForm"><label>kcal<input id="sugTkcal" type="number"></label><label>P g<input id="sugTp" type="number"></label><label>F g<input id="sugTf" type="number"></label><label>C g<input id="sugTc" type="number"></label><label>水分 ml<input id="sugTwater" type="number"></label><label>鉄 mg<input id="sugTiron" type="number" step="0.1"></label></div><button id="sugTargetSave2780" class="sugTargetBtn">目標を保存</button></div></details><div class="sugNutFoot">残量は「設定した1日目標 − 今日の記録」。回復・運動状況で優先順位を変えます。医療的な欠乏診断ではありません。</div>`;h.appendChild(box);document.getElementById('sugTargetSave2780').onclick=saveTargets;fillTargets();render()}
function fillTargets(){const t=state().targets||{};const map=[['sugTkcal',t.kcal??t.targetKcal],['sugTp',t.proteinG??t.targetProteinG],['sugTf',t.fatG??t.targetFatG],['sugTc',t.carbsG??t.targetCarbsG],['sugTwater',t.waterMl??t.targetWaterMl],['sugTiron',t.ironMg??t.targetIronMg]];for(const [id,v] of map){const e=document.getElementById(id);if(e&&v!=null)e.value=v}}
function saveTargets(){const val=id=>{const x=n(document.getElementById(id)?.value);return x!=null&&x>0?x:null};const current=state().targets||{};const t={...current,kcal:val('sugTkcal'),proteinG:val('sugTp'),fatG:val('sugTf'),carbsG:val('sugTc'),waterMl:val('sugTwater'),ironMg:val('sugTiron')};try{window.SuGNutrition?.setTargets?.(t)}catch(_){const s=read(NUT_KEY,{});localStorage.setItem(NUT_KEY,JSON.stringify({...s,targets:t}))}window.dispatchEvent(new CustomEvent('sug:nutrition-targets',{detail:t}));render()}
function render(){mount();const r=analyze(),g=r.gaps,top=document.getElementById('sugNextGap2780'),act=document.getElementById('sugNextActions2780');if(top){const chips=[['KCAL',fmt(g.kcal,'')],['P',fmt(g.proteinG,'g')],['C',fmt(g.carbsG,'g')],['水分',fmt(g.waterMl,'ml')]].map((x,i)=>`<span class="sugGap ${i===3?'blue':''}">${x[0]} あと ${x[1]}</span>`);top.innerHTML=r.targets?chips.join(''):'<span class="sugGap blue">1日の目標を設定すると残量を表示</span>'}if(act){const xs=r.actions.length?r.actions:['食事写真または手入力データを待っています'];act.innerHTML=xs.map(x=>`<div class="sugNextAction">→ ${x}</div>`).join('')}window.__SUG_NEXT_MEAL__=r;window.dispatchEvent(new CustomEvent('sug:next-meal',{detail:r}));return r}
const refresh=()=>setTimeout(render,30);window.addEventListener('sug:nutrition-analysis',refresh);window.addEventListener('sug:nutrition',refresh);window.addEventListener('sug:native-health',refresh);window.addEventListener('sug:food-photo-result',refresh);window.addEventListener('sug:nutrition-targets',refresh);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(render,180),{once:true});else setTimeout(render,180);window.SuGNextMeal={VERSION,analyze,render,saveTargets};
})();